/* SPDX-License-Identifier: GPL-2.0-only OR MIT
 * SPDX-FileCopyrightText: Copyright (c) 2022-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 */

#ifndef NVGPU_NEXT_CLASS_GB10B_H
#define NVGPU_NEXT_CLASS_GB10B_H

#define BLACKWELL_CHANNEL_GPFIFO_A	0xC96FU
#define BLACKWELL_CHANNEL_GPFIFO_B	0xCA6FU
#define BLACKWELL_DMA_COPY_A		0xC9B5U
#define BLACKWELL_A			0xCD97U
#define BLACKWELL_COMPUTE_A		0xCDC0U
#define BLACKWELL_B			0xCE97U
#define BLACKWELL_COMPUTE_B		0xCEC0U
#define BLACKWELL_INLINE_TO_MEMORY_A	0xCD40U
#define NVCEB7_VIDEO_ENCODER		0xCEB7U
#define NVCEB0_VIDEO_DECODER		0xCEB0U
#define NVCEFA_VIDEO_OFA 		0xCEFAU
#define NVCED0_VIDEO_NVJPG		0xCED0U

#endif /* NVGPU_NEXT_CLASS_GB10B_H */
