// SPDX-License-Identifier: GPL-2.0-only OR MIT
// SPDX-FileCopyrightText: Copyright (c) 2024-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.

#include <nvgpu/nvgpu_err.h>
#include <nvgpu/nvgpu_err_info.h>
#include <nvgpu/static_analysis.h>
#include "common/cic/mon/cic_mon_priv.h"
#include "cic_gb10b.h"

/*
 * A flag to enable/disable hw error injection.
 */
#ifdef CONFIG_NVGPU_INJECT_HWERR
#define INJECT_TYPE	(INJECT_HW)
#else
#define INJECT_TYPE	(INJECT_SW)
#endif

/* This look-up table initializes the list of hw units and their errors.
 * It also specifies the error injection mechanism supported, for each error.
 * In case of hw error injection support, this initialization will be overriden
 * by the values provided from the hal layes of corresponding hw units.
 */
struct nvgpu_err_hw_module gb10b_err_lut[] = {
	{
		.name = "host",
		.hw_unit = (u32)NVGPU_ERR_MODULE_HOST,
		.num_instances = 1U,
		.num_errs = 16U,
		.errs = (struct nvgpu_err_desc[]) {
			/* Only used in tu104, gv11b. */
			GPU_CRITERR("pfifo_bind_error",
					GPU_HOST_PFIFO_BIND_ERROR, INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("pfifo_sched_error",
					GPU_HOST_PFIFO_SCHED_ERROR, INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			/* Not used ga10b onwards. */
			GPU_CRITERR("pfifo_chsw_error",
					GPU_HOST_PFIFO_CHSW_ERROR, INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			/* Not used ga10b onwards. */
			GPU_CRITERR("pfifo_memop_error",
					GPU_HOST_PFIFO_MEMOP_TIMEOUT_ERROR,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			/* Not used in ga10b onwards. */
			GPU_CRITERR("pfifo_lb_error",
					GPU_HOST_PFIFO_LB_ERROR, INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			/* Only used in gk20a, tu104, gv11b. */
			GPU_CRITERR("pbus_squash_error",
					GPU_HOST_PBUS_SQUASH_ERROR,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			/* Not used in gb10b. */
			GPU_CRITERR("pbus_fecs_error",
					GPU_HOST_PBUS_FECS_ERROR,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			/* Not used in gb10b. */
			GPU_CRITERR("pbus_timeout_error",
					GPU_HOST_PBUS_TIMEOUT_ERROR,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			/* Only used in tu104, gv11b. */
			GPU_CRITERR("pbdma_timeout_error",
					GPU_HOST_PBDMA_TIMEOUT_ERROR,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			/* Only used in tu104, gv11b. */
			GPU_CRITERR("pbdma_extra_error",
					GPU_HOST_PBDMA_EXTRA_ERROR,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR_RC("pbdma_gpfifo_pb_error",
					GPU_HOST_PBDMA_GPFIFO_PB_ERROR,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR_RC("pbdma_method_error",
					GPU_HOST_PBDMA_METHOD_ERROR,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR_RC("pbdma_signature_error",
					GPU_HOST_PBDMA_SIGNATURE_ERROR,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR_RC("pbdma_hce_error",
					GPU_HOST_PBDMA_HCE_ERROR,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR_RC("pfifo_ctxsw_timeout",
					GPU_HOST_PFIFO_CTXSW_TIMEOUT_ERROR,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),

			/* Only used by gk20a API */
			GPU_CRITERR("pfifo_fb_flush_timeout",
					GPU_HOST_PFIFO_FB_FLUSH_TIMEOUT_ERROR,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
		},
	},
	{
		.name = "sm",
		.hw_unit = (u32)NVGPU_ERR_MODULE_SM,
		.num_instances = 9U,
		.num_errs = 17U,
		.errs = (struct nvgpu_err_desc[]) {
			GPU_NONCRITERR("l1_tag_ecc_corrected",
					GPU_SM_L1_TAG_ECC_CORRECTED,
					INJECT_TYPE,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("l1_tag_ecc_uncorrected",
					GPU_SM_L1_TAG_ECC_UNCORRECTED,
					INJECT_TYPE,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("cbu_ecc_uncorrected",
					GPU_SM_CBU_ECC_UNCORRECTED,
					INJECT_TYPE,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("lrf_ecc_uncorrected",
					GPU_SM_LRF_ECC_UNCORRECTED,
					INJECT_TYPE,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("l1_data_ecc_uncorrected",
					GPU_SM_L1_DATA_ECC_UNCORRECTED,
					INJECT_TYPE,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("icache_l0_data_ecc_uncorrected",
					GPU_SM_ICACHE_L0_DATA_ECC_UNCORRECTED,
					INJECT_TYPE,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("icache_l1_data_ecc_uncorrected",
					GPU_SM_ICACHE_L1_DATA_ECC_UNCORRECTED,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("icache_l0_predecode_ecc_uncorrected",
					GPU_SM_ICACHE_L0_PREDECODE_ECC_UNCORRECTED,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("l1_tag_miss_fifo_ecc_uncorrected",
					GPU_SM_L1_TAG_MISS_FIFO_ECC_UNCORRECTED,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("l1_tag_s2r_pixprf_ecc_uncorrected",
					GPU_SM_L1_TAG_S2R_PIXPRF_ECC_UNCORRECTED,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR_RC("machine_check_error",
					GPU_SM_MACHINE_CHECK_ERROR,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("rams_urf_ecc_uncorrected",
					GPU_SM_RAMS_URF_ECC_UNCORRECTED,
					INJECT_NONE,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("l1_tag_pq_ecc_uncorrected",
					GPU_SM_L1_TAG_PQ_ECC_UNCORRECTED,
					INJECT_NONE,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("l1_data_tbm_ecc_uncorrected",
					GPU_SM_L1_DATA_TBM_ECC_UNCORRECTED,
					INJECT_NONE,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("rams_decc_ecc_uncorrected",
					GPU_SM_RAMS_DECC_ECC_UNCORRECTED,
					INJECT_NONE,
					NULL, NULL,
					NULL, NULL, 0, 0),
			/* RC is trigerred for each fatal non-ECC SM exception
			 * due to the sructure of the ISR.
			 */
			GPU_CRITERR_RC("poison_error",
					GPU_SM_POISON_ERROR,
					INJECT_NONE,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR_RC("cga_error",
					GPU_SM_CGA_ERROR,
					INJECT_NONE,
					NULL, NULL,
					NULL, NULL, 0, 0),
		},
	},
	{
		.name = "fecs",
		.hw_unit = (u32)NVGPU_ERR_MODULE_FECS,
		.num_instances = 1U,
		.num_errs = 9U,
		.errs = (struct nvgpu_err_desc[]) {
			GPU_NONCRITERR("falcon_imem_ecc_corrected",
					GPU_FECS_FALCON_IMEM_ECC_CORRECTED,
					INJECT_TYPE,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("falcon_imem_ecc_uncorrected",
					GPU_FECS_FALCON_IMEM_ECC_UNCORRECTED,
					INJECT_TYPE,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("falcon_dmem_ecc_uncorrected",
					GPU_FECS_FALCON_DMEM_ECC_UNCORRECTED,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("ctxsw_watchdog_timeout",
					GPU_FECS_CTXSW_WATCHDOG_TIMEOUT,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR_RC("ctxsw_crc_mismatch",
					GPU_FECS_CTXSW_CRC_MISMATCH,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR_RC("fault_during_ctxsw",
					GPU_FECS_FAULT_DURING_CTXSW,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("ctxsw_init_error",
					GPU_FECS_CTXSW_INIT_ERROR,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("ctxsw_poison_error",
					GPU_FECS_CTXSW_POISON_ERROR,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("ctx_load_after_halt",
					GPU_FECS_CTX_LOAD_AFTER_HALT,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
		},
	},
	{
		.name = "gpccs",
		.hw_unit = (u32)NVGPU_ERR_MODULE_GPCCS,
		.num_instances = 1U,
		.num_errs = 9U,
		.errs = (struct nvgpu_err_desc[]) {
			GPU_NONCRITERR("falcon_imem_ecc_corrected",
					GPU_GPCCS_FALCON_IMEM_ECC_CORRECTED,
					INJECT_TYPE,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("falcon_imem_ecc_uncorrected",
					GPU_GPCCS_FALCON_IMEM_ECC_UNCORRECTED,
					INJECT_TYPE,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("falcon_dmem_ecc_uncorrected",
					GPU_GPCCS_FALCON_DMEM_ECC_UNCORRECTED,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("poison_error",
					GPU_GPCCS_POISON_ERROR,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("fault_during_ctxsw",
					GPU_GPCCS_FAULT_DURING_CTXSW,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("watchdog_expired",
					GPU_GPCCS_WATCHDOG_EXPIRED,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("bsi_cmd_parity_error",
					GPU_GPCCS_BSI_CMD_PARITY_ERROR,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("bsi_cmd_pkt_dropped_error",
					GPU_GPCCS_BSI_CMD_PKT_DROPPED_ERROR,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("bsi_cmd_addr_oob",
					GPU_GPCCS_BSI_CMD_ADDR_OOB,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
		},
	},
	{
		.name = "mmu",
		.hw_unit = (u32)NVGPU_ERR_MODULE_MMU,
		.num_instances = 1U,
		.num_errs = 2U,
		.errs = (struct nvgpu_err_desc[]) {
			GPU_CRITERR("l1tlb_sa_data_ecc_uncorrected",
					GPU_MMU_L1TLB_SA_DATA_ECC_UNCORRECTED,
					INJECT_TYPE,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("l1tlb_fa_data_ecc_uncorrected",
					GPU_MMU_L1TLB_FA_DATA_ECC_UNCORRECTED,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
		},
	},
	{
		.name = "gcc",
		.hw_unit = (u32)NVGPU_ERR_MODULE_GCC,
		.num_instances = 1U,
		.num_errs = 2U,
		.errs = (struct nvgpu_err_desc[]) {
			GPU_CRITERR("l15_ecc_uncorrected",
					GPU_GCC_L15_ECC_UNCORRECTED,
					INJECT_TYPE,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("poison_error",
					GPU_GCC_POISON_ERROR,
					INJECT_TYPE,
					NULL, NULL,
					NULL, NULL, 0, 0),
		},
	},
	{
		.name = "pmu",
		.hw_unit = (u32)NVGPU_ERR_MODULE_PMU,
		.num_instances = 1U,
		.num_errs = 10U,
		.errs = (struct nvgpu_err_desc[]) {
			GPU_CRITERR("pmu_nvriscv_brom_failure",
					GPU_PMU_NVRISCV_BROM_FAILURE,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("pmu_access_timeout",
					GPU_PMU_ACCESS_TIMEOUT_UNCORRECTED,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("pmu_mpu_ecc_uncorrected",
					GPU_PMU_MPU_ECC_UNCORRECTED,
					INJECT_NONE,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("pmu_illegal_access_uncorrected",
					GPU_PMU_ILLEGAL_ACCESS_UNCORRECTED,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("pmu_imem_ecc_uncorrected",
					GPU_PMU_IMEM_ECC_UNCORRECTED,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("pmu_dcls_uncorrected",
					GPU_PMU_DCLS_UNCORRECTED,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("pmu_dmem_ecc_uncorrected",
					GPU_PMU_DMEM_ECC_UNCORRECTED,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("pmu_wdt_uncorrected",
					GPU_PMU_WDT_UNCORRECTED,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("pmu_reg_ecc_uncorrected",
					GPU_PMU_REG_ECC_UNCORRECTED,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("pmu_bar0_error_timeout",
					GPU_PMU_BAR0_ERROR_TIMEOUT,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
		},
	},
	{
		.name = "pgraph",
		.hw_unit = (u32)NVGPU_ERR_MODULE_PGRAPH,
		.num_instances = 1U,
		.num_errs = 25U,
		.errs = (struct nvgpu_err_desc[]) {
			GPU_CRITERR_RC("fe_exception",
					GPU_PGRAPH_FE_EXCEPTION,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR_RC("memfmt_exception",
					GPU_PGRAPH_MEMFMT_EXCEPTION,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR_RC("pd_exception",
					GPU_PGRAPH_PD_EXCEPTION,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR_RC("scc_exception",
					GPU_PGRAPH_SCC_EXCEPTION,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR_RC("ds_exception",
					GPU_PGRAPH_DS_EXCEPTION,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR_RC("ssync_exception",
					GPU_PGRAPH_SSYNC_EXCEPTION,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR_RC("mme_exception",
					GPU_PGRAPH_MME_EXCEPTION,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR_RC("sked_exception",
					GPU_PGRAPH_SKED_EXCEPTION,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("be_crop_exception",
					GPU_PGRAPH_BE_CROP_EXCEPTION,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("be_zrop_exception",
					GPU_PGRAPH_BE_ZROP_EXCEPTION,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("mpc_exception",
					GPU_PGRAPH_MPC_EXCEPTION,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR_RC("illegal_notify_error",
					GPU_PGRAPH_ILLEGAL_NOTIFY_ERROR,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR_RC("illegal_method_error",
					GPU_PGRAPH_ILLEGAL_METHOD_ERROR,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR_RC("illegal_class_error",
					GPU_PGRAPH_ILLEGAL_CLASS_ERROR,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR_RC("class_error",
					GPU_PGRAPH_CLASS_ERROR,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("gpc_gfx_prop_exception",
					GPU_PGRAPH_GPC_GFX_PROP_EXCEPTION,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("gpc_gfx_zcull_exception",
					GPU_PGRAPH_GPC_GFX_ZCULL_EXCEPTION,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("gpc_gfx_setup_exception",
					GPU_PGRAPH_GPC_GFX_SETUP_EXCEPTION,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("gpc_gfx_pes_exception",
					GPU_PGRAPH_GPC_GFX_PES_EXCEPTION,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("gpc_gfx_tpc_pe_exception",
					GPU_PGRAPH_GPC_GFX_TPC_PE_EXCEPTION,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR_RC("mme_fe1_exception",
					GPU_PGRAPH_MME_FE1_EXCEPTION,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("tpccs_poison_error",
					GPU_PGRAPH_TPCCS_POISON_ERROR,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("tpccs_fault_during_ctxsw",
					GPU_PGRAPH_TPCCS_FAULT_DURING_CTXSW,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("rastwod_exception",
					GPU_PGRAPH_RASTWOD_EXCEPTION,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("gpc_wdxps_exception",
					GPU_PGRAPH_GPC_WDXPS_EXCEPTION,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
		},
	},
	{
		.name = "ltc",
		.hw_unit = (u32)NVGPU_ERR_MODULE_LTC,
		.num_instances = 1U,
		.num_errs = 7U,
		.errs = (struct nvgpu_err_desc[]) {
			GPU_NONCRITERR("cache_dstg_ecc_corrected",
					GPU_LTC_CACHE_DSTG_ECC_CORRECTED,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR_QUIESCE("cache_dstg_ecc_uncorrected",
					GPU_LTC_CACHE_DSTG_ECC_UNCORRECTED,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR_QUIESCE("cache_tstg_ecc_uncorrected",
					GPU_LTC_CACHE_TSTG_ECC_UNCORRECTED,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR_QUIESCE("cache_rstg_cbc_ecc_uncorrected",
					GPU_LTC_CACHE_RSTG_CBC_ECC_UNCORRECTED,
					INJECT_NONE,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR_QUIESCE("cache_xbar_intfc_ecc_uncorrected",
					GPU_LTC_CACHE_XBAR_INTFC_ECC_UNCORRECTED,
					INJECT_NONE,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR_QUIESCE("cache_uncorrected_error",
					GPU_LTC_CACHE_UNCORRECTED_ERROR,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("cache_unsupported_ecc_error",
					GPU_LTC_CACHE_UNSUPPORTED_ECC_ERROR,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
		},
	},
	{
		.name = "hubmmu",
		.hw_unit = (u32)NVGPU_ERR_MODULE_HUBMMU,
		.num_instances = 1U,
		.num_errs = 9U,
		.errs = (struct nvgpu_err_desc[]) {
			/* GPU reset is not needed for HUBMMU ECC errors
			 * if error reissue is enabled.
			 * See safety IAS.
			 */
			GPU_CRITERR("hubmmu_l2tlb_sa_data_ecc_uncorrected",
					GPU_HUBMMU_L2TLB_SA_DATA_ECC_UNCORRECTED,
					INJECT_TYPE,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("hubmmu_tlb_sa_data_ecc_uncorrected",
					GPU_HUBMMU_TLB_SA_DATA_ECC_UNCORRECTED,
					INJECT_TYPE,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("hubmmu_pte_data_ecc_uncorrected",
					GPU_HUBMMU_PTE_DATA_ECC_UNCORRECTED,
					INJECT_TYPE,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("hubmmu_pde0_data_ecc_uncorrected",
					GPU_HUBMMU_PDE0_DATA_ECC_UNCORRECTED,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR_RC("hubmmu_page_fault_other_fault_notify_error",
					GPU_HUBMMU_PAGE_FAULT_OTHER_FAULT_NOTIFY_ERROR,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("hubmmu_page_fault_nonreplayable_fault_overflow_error",
					GPU_HUBMMU_PAGE_FAULT_NONREPLAYABLE_FAULT_OVERFLOW_ERROR,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("hubmmu_page_fault_replayable_fault_overflow_error",
					GPU_HUBMMU_PAGE_FAULT_REPLAYABLE_FAULT_OVERFLOW_ERROR,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR_RC("hubmmu_page_fault_replayable_fault_notify_error",
					GPU_HUBMMU_PAGE_FAULT_REPLAYABLE_FAULT_NOTIFY_ERROR,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR_RC("hubmmu_page_fault_nonreplayable_fault_notify_error",
					GPU_HUBMMU_PAGE_FAULT_NONREPLAYABLE_FAULT_NOTIFY_ERROR,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
		},
	},
	{
		.name = "pri",
		.hw_unit = (u32)NVGPU_ERR_MODULE_PRI,
		.num_instances = 1U,
		.num_errs = 2U,
		.errs = (struct nvgpu_err_desc[]) {
			GPU_CRITERR("pri_timeout_error",
					GPU_PRI_TIMEOUT_ERROR,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("pri_access_violation",
					GPU_PRI_ACCESS_VIOLATION,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
		},
	},
	{
		.name = "ce",
		.hw_unit = (u32)NVGPU_ERR_MODULE_CE,
		.num_instances = 1U,
		.num_errs = 7U,
		.errs = (struct nvgpu_err_desc[]) {
			GPU_CRITERR_RC("ce_launch_error",
					GPU_CE_LAUNCH_ERROR,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
#ifdef CONFIG_NVGPU_NON_FUSA
			GPU_CRITERR_QUIESCE("ce_method_buffer_fault",
					GPU_CE_METHOD_BUFFER_FAULT,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR_QUIESCE("ce_fbuf_crc_fail",
					GPU_CE_FBUF_CRC_FAIL,
					INJECT_NONE,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR_QUIESCE("ce_fbuf_magic_chk_fail",
					GPU_CE_FBUF_MAGIC_CHK_FAIL,
					INJECT_NONE,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR_QUIESCE("ce_invalid_config",
					GPU_CE_INVALID_CONFIG,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
#endif
			GPU_CRITERR_RC("ce_ctx_load_after_halt",
					GPU_CE_CTX_LOAD_AFTER_HALT,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR_RC("ce_cc_no_resources",
					GPU_CE_CC_NO_RESOURCES,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
		},
	},
	{
		.name = "gsp_acr",
		.hw_unit = (u32)NVGPU_ERR_MODULE_GSP_ACR,
		.num_instances = 1U,
		.num_errs = 17U,
		.errs = (struct nvgpu_err_desc[]) {
			GPU_CRITERR("gsp_acr_nvriscv_brom_failure",
					GPU_GSP_ACR_NVRISCV_BROM_FAILURE,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("gpu_gsp_acr_emem_ecc_uncorrected",
					GPU_GSP_ACR_EMEM_ECC_UNCORRECTED,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("gpu_gsp_acr_reg_access_timeout_uncorrected",
					GPU_GSP_ACR_REG_ACCESS_TIMEOUT_UNCORRECTED,
					INJECT_NONE,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("gpu_gsp_acr_illegal_access_uncorrected",
					GPU_GSP_ACR_ILLEGAL_ACCESS_UNCORRECTED,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("gpu_gsp_acr_imem_ecc_uncorrected",
					GPU_GSP_ACR_IMEM_ECC_UNCORRECTED,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("gpu_gsp_acr_dcls_uncorrected",
					GPU_GSP_ACR_DCLS_UNCORRECTED,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("gpu_gsp_acr_dmem_ecc_uncorrected",
					GPU_GSP_ACR_DMEM_ECC_UNCORRECTED,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("gpu_gsp_acr_wdt_uncorrected",
					GPU_GSP_ACR_WDT_UNCORRECTED,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("gpu_gsp_acr_reg_ecc_uncorrected",
					GPU_GSP_ACR_REG_ECC_UNCORRECTED,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("gpu_gsp_acr_fecs_pkc_lssig_failure",
					GPU_GSP_ACR_FECS_PKC_LSSIG_FAILURE,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("gpu_gsp_acr_gpccs_pkc_lssig_failure",
					GPU_GSP_ACR_GPCCS_PKC_LSSIG_FAILURE,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("gpu_gsp_acr_lspmu_pkc_lssig_failure",
					GPU_GSP_ACR_LSPMU_PKC_LSSIG_FAILURE,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("gpu_gsp_acr_nvdec_pkc_lssig_failure",
					GPU_GSP_ACR_NVDEC_PKC_LSSIG_FAILURE,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("gpu_gsp_acr_nvjpg_pkc_lssig_failure",
					GPU_GSP_ACR_NVJPG_PKC_LSSIG_FAILURE,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("gpu_gsp_acr_ofa_pkc_lssig_failure",
					GPU_GSP_ACR_OFA_PKC_LSSIG_FAILURE,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("gpu_gsp_acr_nvenc_pkc_lssig_failure",
					GPU_GSP_ACR_NVENC_PKC_LSSIG_FAILURE,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("gpu_gsp_acr_cmd_timeout_uncorrected",
					GPU_GSP_ACR_CMD_TIMEOUT_UNCORRECTED,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
		},
	},
	{
		.name = "gsp_sched",
		.hw_unit = (u32)NVGPU_ERR_MODULE_GSP_SCHED,
		.num_instances = 1U,
		.num_errs = 11U,
		.errs = (struct nvgpu_err_desc[]) {
			GPU_CRITERR("gsp_sched_nvriscv_brom_failure",
					GPU_GSP_SCHED_NVRISCV_BROM_FAILURE,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("gpu_gsp_sched_emem_ecc_uncorrected",
					GPU_GSP_SCHED_EMEM_ECC_UNCORRECTED,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("gpu_gsp_sched_reg_access_timeout_uncorrected",
					GPU_GSP_SCHED_REG_ACCESS_TIMEOUT_UNCORRECTED,
					INJECT_NONE,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("gpu_gsp_sched_illegal_access_uncorrected",
					GPU_GSP_SCHED_ILLEGAL_ACCESS_UNCORRECTED,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("gpu_gsp_sched_imem_ecc_uncorrected",
					GPU_GSP_SCHED_IMEM_ECC_UNCORRECTED,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("gpu_gsp_sched_dcls_uncorrected",
					GPU_GSP_SCHED_DCLS_UNCORRECTED,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("gpu_gsp_sched_dmem_ecc_uncorrected",
					GPU_GSP_SCHED_DMEM_ECC_UNCORRECTED,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("gpu_gsp_sched_wdt_uncorrected",
					GPU_GSP_SCHED_WDT_UNCORRECTED,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("gpu_gsp_sched_reg_ecc_uncorrected",
					GPU_GSP_SCHED_REG_ECC_UNCORRECTED,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR_QUIESCE("gpu_gsp_sched_uncorrected_err",
					GPU_GSP_SCHED_UNCORRECTED_ERR,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_NONCRITERR("gpu_gsp_sched_corrected_err",
					GPU_GSP_SCHED_CORRECTED_ERR,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
		},
	},
	{
		.name = "fuse",
		.hw_unit = (u32)NVGPU_ERR_MODULE_FUSE,
		.num_instances = 1U,
		.num_errs = 1U,
		.errs = (struct nvgpu_err_desc[]) {
			GPU_CRITERR_QUIESCE("gpu_fuse_reg_parity",
					GPU_FUSE_REG_PARITY,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
		},
	},
	{
		.name = "ofa",
		.hw_unit = (u32)NVGPU_ERR_MODULE_OFA,
		.num_instances = 1U,
		.num_errs = 2U,
		.errs = (struct nvgpu_err_desc[]) {
			GPU_CRITERR("gpu_ofa_uncorrected_err",
					GPU_OFA_UNCORRECTED_ERR,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_NONCRITERR("gpu_ofa_corrected_err",
					GPU_OFA_CORRECTED_ERR,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
		},
	},
	{
		.name = "nvenc",
		.hw_unit = (u32)NVGPU_ERR_MODULE_NVENC,
		.num_instances = 2U,
		.num_errs = 2U,
		.errs = (struct nvgpu_err_desc[]) {
			GPU_CRITERR("gpu_nvenc_uncorrected_err",
					GPU_NVENC_UNCORRECTED_ERR,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_NONCRITERR("gpu_nvenc_corrected_err",
					GPU_NVENC_CORRECTED_ERR,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
		},
	},
	{
		.name = "nvdec",
		.hw_unit = (u32)NVGPU_ERR_MODULE_NVDEC,
		.num_instances = 2U,
		.num_errs = 1U,
		.errs = (struct nvgpu_err_desc[]) {
			GPU_CRITERR("gpu_nvdec_uncorrected_err",
					GPU_NVDEC_UNCORRECTED_ERR,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
		},
	},
	{
		.name = "nvjpg",
		.hw_unit = (u32)NVGPU_ERR_MODULE_NVJPG,
		.num_instances = 2U,
		.num_errs = 1U,
		.errs = (struct nvgpu_err_desc[]) {
			GPU_CRITERR("gpu_nvjpg_uncorrected_err",
					GPU_NVJPG_UNCORRECTED_ERR,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
		},
	},
	{
		.name = "sysctrl",
		.hw_unit = (u32)NVGPU_ERR_MODULE_SYSCTRL,
		.num_instances = 1U,
		.num_errs = 1U,
		.errs = (struct nvgpu_err_desc[]) {
			GPU_CRITERR_QUIESCE("sysctrl_uncorrected_err",
					GPU_SYSCTRL_UNCORRECTED_ERR,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
		},
	},
	{
		.name = "ctc_chi",
		.hw_unit = (u32)NVGPU_ERR_MODULE_CTCCHI,
		.num_instances = 1U,
		.num_errs = 1U,
		.errs = (struct nvgpu_err_desc[]) {
			GPU_CRITERR_QUIESCE("ctc_chi_uncorrected_err",
					GPU_CTC_CHI_UNCORRECTED_ERR,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
		},
	},
	{
		.name = "lrc",
		.hw_unit = (u32)NVGPU_ERR_MODULE_LRC,
		.num_instances = 1U,
		.num_errs = 2U,
		.errs = (struct nvgpu_err_desc[]) {
			GPU_CRITERR_QUIESCE("lrc_sram_ecc_uncorrected",
					GPU_LRC_SRAM_ECC_UNCORRECTED,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR("lrc_sram_ecc_unsupported",
					GPU_LRC_SRAM_ECC_UNSUPPORTED,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
		},
	},
	{
		.name = "xal",
		.hw_unit = (u32)NVGPU_ERR_MODULE_XAL,
		.num_instances = 1U,
		.num_errs = 7U,
		.errs = (struct nvgpu_err_desc[]) {
			GPU_NONCRITERR("gpu_xal_ep_ecc_corrected",
					GPU_XAL_EP_ECC_CORRECTED,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR_QUIESCE("gpu_xal_ep_ecc_uncorrected",
					GPU_XAL_EP_ECC_UNCORRECTED,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR_QUIESCE("gpu_xal_ep_parity_error",
					GPU_XAL_EP_PARITY_ERROR,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR_QUIESCE("gpu_xal_ep_uncorrected_error",
					GPU_XAL_EP_UNCORRECTED_ERROR,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR_QUIESCE("gpu_xal_ep_ingress_poison_error",
					GPU_XAL_EP_INGRESS_POISON_ERROR,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR_QUIESCE("gpu_xal_ep_egress_poison_error",
					GPU_XAL_EP_EGRESS_POISON_ERROR,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
			GPU_CRITERR_QUIESCE("gpu_xal_ep_decoupler_error",
					GPU_XAL_EP_DECOUPLER_ERROR,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
		},
	},
	{
		.name = "xtl",
		.hw_unit = (u32)NVGPU_ERR_MODULE_XTL,
		.num_instances = 1U,
		.num_errs = 1U,
		.errs = (struct nvgpu_err_desc[]) {
			GPU_CRITERR_QUIESCE("gpu_xtl_ep_ec_uncorrected_err",
					GPU_XTL_EP_EC_UNCORRECTED_ERR,
					INJECT_SW,
					NULL, NULL,
					NULL, NULL, 0, 0),
		},
	},
};

u32 size_of_gb10b_lut = (u32)(sizeof(gb10b_err_lut) /
					sizeof(struct nvgpu_err_hw_module));
