/* SPDX-License-Identifier: MIT */
/*
 * SPDX-FileCopyrightText: Copyright (c) 2023-2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#ifndef T264_HWPM_PERFMON_DEVICE_INDEX_H
#define T264_HWPM_PERFMON_DEVICE_INDEX_H

enum t264_hwpm_perfmon_device_index {
	T264_SYSTEM_MSS_HUB0_PERFMON_DEVICE_NODE_INDEX,
	T264_HWPM_PERFMON_DEVICE_NODE_INDEX,
	T264_CPU_CORE0_PERFMON_DEVICE_NODE_INDEX,
	T264_CPU_CORE1_PERFMON_DEVICE_NODE_INDEX,
	T264_CPU_CORE2_PERFMON_DEVICE_NODE_INDEX,
	T264_CPU_CORE3_PERFMON_DEVICE_NODE_INDEX,
	T264_CPU_CORE4_PERFMON_DEVICE_NODE_INDEX,
	T264_CPU_CORE5_PERFMON_DEVICE_NODE_INDEX,
	T264_CPU_CORE6_PERFMON_DEVICE_NODE_INDEX,
	T264_CPU_CORE7_PERFMON_DEVICE_NODE_INDEX,
	T264_CPU_CORE8_PERFMON_DEVICE_NODE_INDEX,
	T264_CPU_CORE9_PERFMON_DEVICE_NODE_INDEX,
	T264_CPU_CORE10_PERFMON_DEVICE_NODE_INDEX,
	T264_CPU_CORE11_PERFMON_DEVICE_NODE_INDEX,
	T264_CPU_CORE12_PERFMON_DEVICE_NODE_INDEX,
	T264_CPU_CORE13_PERFMON_DEVICE_NODE_INDEX,
	T264_UCF_MSW0_PERFMON_DEVICE_NODE_INDEX,
	T264_UCF_MSW1_PERFMON_DEVICE_NODE_INDEX,
	T264_UCF_MSW2_PERFMON_DEVICE_NODE_INDEX,
	T264_UCF_MSW3_PERFMON_DEVICE_NODE_INDEX,
	T264_UCF_MSW4_PERFMON_DEVICE_NODE_INDEX,
	T264_UCF_MSW5_PERFMON_DEVICE_NODE_INDEX,
	T264_UCF_MSW6_PERFMON_DEVICE_NODE_INDEX,
	T264_UCF_MSW7_PERFMON_DEVICE_NODE_INDEX,
	T264_UCF_MSW8_PERFMON_DEVICE_NODE_INDEX,
	T264_UCF_MSW9_PERFMON_DEVICE_NODE_INDEX,
	T264_UCF_MSW10_PERFMON_DEVICE_NODE_INDEX,
	T264_UCF_MSW11_PERFMON_DEVICE_NODE_INDEX,
	T264_UCF_MSW12_PERFMON_DEVICE_NODE_INDEX,
	T264_UCF_MSW13_PERFMON_DEVICE_NODE_INDEX,
	T264_UCF_MSW14_PERFMON_DEVICE_NODE_INDEX,
	T264_UCF_MSW15_PERFMON_DEVICE_NODE_INDEX,
	T264_MSS_CHANNEL_PARTA0_PERFMON_DEVICE_NODE_INDEX,
	T264_MSS_CHANNEL_PARTA1_PERFMON_DEVICE_NODE_INDEX,
	T264_MSS_CHANNEL_PARTA2_PERFMON_DEVICE_NODE_INDEX,
	T264_MSS_CHANNEL_PARTA3_PERFMON_DEVICE_NODE_INDEX,
	T264_MSS_CHANNEL_PARTB0_PERFMON_DEVICE_NODE_INDEX,
	T264_MSS_CHANNEL_PARTB1_PERFMON_DEVICE_NODE_INDEX,
	T264_MSS_CHANNEL_PARTB2_PERFMON_DEVICE_NODE_INDEX,
	T264_MSS_CHANNEL_PARTB3_PERFMON_DEVICE_NODE_INDEX,
	T264_MSS_CHANNEL_PARTC0_PERFMON_DEVICE_NODE_INDEX,
	T264_MSS_CHANNEL_PARTC1_PERFMON_DEVICE_NODE_INDEX,
	T264_MSS_CHANNEL_PARTC2_PERFMON_DEVICE_NODE_INDEX,
	T264_MSS_CHANNEL_PARTC3_PERFMON_DEVICE_NODE_INDEX,
	T264_MSS_CHANNEL_PARTD0_PERFMON_DEVICE_NODE_INDEX,
	T264_MSS_CHANNEL_PARTD1_PERFMON_DEVICE_NODE_INDEX,
	T264_MSS_CHANNEL_PARTD2_PERFMON_DEVICE_NODE_INDEX,
	T264_MSS_CHANNEL_PARTD3_PERFMON_DEVICE_NODE_INDEX,
	T264_UCF_CSW0_PERFMON_DEVICE_NODE_INDEX,
	T264_UCF_CSW1_PERFMON_DEVICE_NODE_INDEX,
	T264_UCF_MSS_HUB0_PERFMON_DEVICE_NODE_INDEX,
	T264_UCF_MSS_HUB1_PERFMON_DEVICE_NODE_INDEX,
	T264_UCF_TCU0_PERFMON_DEVICE_NODE_INDEX,
	T264_UCF_TCU1_PERFMON_DEVICE_NODE_INDEX,
	T264_UCF_PSW0_PERFMON_DEVICE_NODE_INDEX,
	T264_UCF_PSW1_PERFMON_DEVICE_NODE_INDEX,
	T264_UCF_PSW2_PERFMON_DEVICE_NODE_INDEX,
	T264_UCF_PSW3_PERFMON_DEVICE_NODE_INDEX,
	T264_UCF_TCU3_PERFMON_DEVICE_NODE_INDEX,
	T264_UCF_MSS_HUB2_PERFMON_DEVICE_NODE_INDEX,
	T264_UCF_TCU2_PERFMON_DEVICE_NODE_INDEX,
	T264_VI0_PERFMON_DEVICE_NODE_INDEX,
	T264_VI1_PERFMON_DEVICE_NODE_INDEX,
	T264_ISP0_PERFMON_DEVICE_NODE_INDEX,
	T264_ISP1_PERFMON_DEVICE_NODE_INDEX,
	T264_VICA0_PERFMON_DEVICE_NODE_INDEX,
	T264_PVAC0_PERFMON_DEVICE_NODE_INDEX,
	T264_PVAV0_PERFMON_DEVICE_NODE_INDEX,
	T264_PVAV1_PERFMON_DEVICE_NODE_INDEX,
	T264_VISION_MSS_HUB0_PERFMON_DEVICE_NODE_INDEX,
	T264_VISION_MSS_HUB1_PERFMON_DEVICE_NODE_INDEX,
	T264_PVAP0_PERFMON_DEVICE_NODE_INDEX,
	T264_PVAP1_PERFMON_DEVICE_NODE_INDEX,
	T264_DISP_USB_MSS_HUB0_PERFMON_DEVICE_NODE_INDEX,
	T264_DISP_USB_TCU0_PERFMON_DEVICE_NODE_INDEX,
	T264_OCU0_PERFMON_DEVICE_NODE_INDEX,
	T264_UPHY0_MSS_HUB0_PERFMON_DEVICE_NODE_INDEX,
	T264_UPHY0_MSS_HUB1_PERFMON_DEVICE_NODE_INDEX,
	T264_PMA_DEVICE_NODE_INDEX,
	T264_RTR_DEVICE_NODE_INDEX
};

#endif
