# SPDX-FileCopyrightText: Copyright (c) 2022-2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: GPL-2.0-only

#
# NVPPS driver and PTP Framework.
#

nvpps-y := nvpps_main.o ptp-notifier.o

obj-m := nvpps.o
