/* SPDX-License-Identifier: GPL-2.0-only OR MIT
 * SPDX-FileCopyrightText: Copyright (c) 2019-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 */


#ifndef NVGPU_BOARDOBJGRP_CLASSES_H
#define NVGPU_BOARDOBJGRP_CLASSES_H

/* Enumeration of BOARDOBJGRP class IDs. Used as "classId" argument for
 * communications between Kernel and PMU via the various generic
 * BOARDOBJGRP interfaces.
*/

/* Clk unit */
#define NV_PMU_CLK_BOARDOBJGRP_CLASS_ID__FIRST			0x01U
#define NV_PMU_CLK_BOARDOBJGRP_CLASS_ID_CLK_DOMAIN		\
			(NV_PMU_CLK_BOARDOBJGRP_CLASS_ID__FIRST + 0x00U)
#define NV_PMU_CLK_BOARDOBJGRP_CLASS_ID_CLK_PROG		\
			(NV_PMU_CLK_BOARDOBJGRP_CLASS_ID__FIRST + 0x01U)
#define NV_PMU_CLK_BOARDOBJGRP_CLASS_ID_VIN_DEVICE		\
			(NV_PMU_CLK_BOARDOBJGRP_CLASS_ID__FIRST + 0x02U)
#define NV_PMU_CLK_BOARDOBJGRP_CLASS_ID_FLL_DEVICE		\
			(NV_PMU_CLK_BOARDOBJGRP_CLASS_ID__FIRST + 0x03U)
#define NV_PMU_CLK_BOARDOBJGRP_CLASS_ID_CLK_VF_POINT		\
			(NV_PMU_CLK_BOARDOBJGRP_CLASS_ID__FIRST + 0x04U)
#define NV_PMU_CLK_BOARDOBJGRP_CLASS_ID_CLK_FREQ_CONTROLLER	\
			(NV_PMU_CLK_BOARDOBJGRP_CLASS_ID__FIRST + 0x05U)
#define NV_PMU_CLK_BOARDOBJGRP_CLASS_ID_CLK_FREQ_DOMAIN		\
			(NV_PMU_CLK_BOARDOBJGRP_CLASS_ID__FIRST + 0x07U)
#define NV_PMU_CLK_BOARDOBJGRP_CLASS_ID_CLK_ENUM			\
			(NV_PMU_CLK_BOARDOBJGRP_CLASS_ID__FIRST + 0x09U)
#define NV_PMU_CLK_BOARDOBJGRP_CLASS_ID_CLK_VF_REL			\
			(NV_PMU_CLK_BOARDOBJGRP_CLASS_ID__FIRST + 0x0AU)
#define NV_PMU_CLK_BOARDOBJGRP_CLASS_ID_CLK_PROP_REGIME		\
			(NV_PMU_CLK_BOARDOBJGRP_CLASS_ID__FIRST + 0x0BU)
#define NV_PMU_CLK_BOARDOBJGRP_CLASS_ID_CLK_PROP_TOP	\
			(NV_PMU_CLK_BOARDOBJGRP_CLASS_ID__FIRST + 0x0CU)
#define NV_PMU_CLK_BOARDOBJGRP_CLASS_ID_CLK_PROP_TOP_REL	\
			(NV_PMU_CLK_BOARDOBJGRP_CLASS_ID__FIRST + 0x0DU)
#define NV_PMU_CLK_BOARDOBJGRP_CLASS_ID_CLK_VF_TUPLE	\
			(NV_PMU_CLK_BOARDOBJGRP_CLASS_ID__FIRST + 0x10U)
#define NV_PMU_CLK_BOARDOBJGRP_CLASS_ID__LAST			\
			(NV_PMU_CLK_BOARDOBJGRP_CLASS_ID__FIRST + 0x10U)

/* Volt unit */
#define NV_PMU_VOLT_BOARDOBJGRP_CLASS_ID__FIRST			\
			(NV_PMU_CLK_BOARDOBJGRP_CLASS_ID__LAST + 0x01U)
#define NV_PMU_VOLT_BOARDOBJGRP_CLASS_ID_VOLT_RAIL		\
			(NV_PMU_VOLT_BOARDOBJGRP_CLASS_ID__FIRST + 0x00U)
#define NV_PMU_VOLT_BOARDOBJGRP_CLASS_ID_VOLT_DEVICE		\
			(NV_PMU_VOLT_BOARDOBJGRP_CLASS_ID__FIRST + 0x01U)
#define NV_PMU_VOLT_BOARDOBJGRP_CLASS_ID_VOLT_POLICY		\
			(NV_PMU_VOLT_BOARDOBJGRP_CLASS_ID__FIRST + 0x02U)
#define NV_PMU_VOLT_BOARDOBJGRP_CLASS_ID__LAST			\
			(NV_PMU_VOLT_BOARDOBJGRP_CLASS_ID__FIRST + 0x04U)

/* Perf unit */
#define NV_PMU_PERF_BOARDOBJGRP_CLASS_ID__FIRST			\
			(NV_PMU_VOLT_BOARDOBJGRP_CLASS_ID__LAST + 0x01U)
#define NV_PMU_PERF_BOARDOBJGRP_CLASS_ID_VFE_VAR		\
			(NV_PMU_PERF_BOARDOBJGRP_CLASS_ID__FIRST + 0x00U)
#define NV_PMU_PERF_BOARDOBJGRP_CLASS_ID_VFE_EQU		\
			(NV_PMU_PERF_BOARDOBJGRP_CLASS_ID__FIRST + 0x01U)
#define NV_PMU_PERF_BOARDOBJGRP_CLASS_ID_PSTATE			\
			(NV_PMU_PERF_BOARDOBJGRP_CLASS_ID__FIRST + 0x03U)
#define NV_PMU_PERF_BOARDOBJGRP_CLASS_ID__LAST			\
			(NV_PMU_PERF_BOARDOBJGRP_CLASS_ID__FIRST + 0x05U)

/* Therm unit */
#define NV_PMU_THERM_BOARDOBJGRP_CLASS_ID__FIRST		\
			(NV_PMU_PERF_BOARDOBJGRP_CLASS_ID__LAST + 0x01U)
#define NV_PMU_THERM_BOARDOBJGRP_CLASS_ID_THERM_DEVICE		\
			(NV_PMU_THERM_BOARDOBJGRP_CLASS_ID__FIRST + 0x00U)
#define NV_PMU_THERM_BOARDOBJGRP_CLASS_ID_THERM_CHANNEL		\
			(NV_PMU_THERM_BOARDOBJGRP_CLASS_ID__FIRST + 0x01U)
#define NV_PMU_THERM_BOARDOBJGRP_CLASS_ID__LAST			\
			(NV_PMU_THERM_BOARDOBJGRP_CLASS_ID__FIRST + 0x03U)

#endif /* NVGPU_BOARDOBJGRP_CLASSES_H */
