/* SPDX-License-Identifier: GPL-2.0-only OR MIT
 * SPDX-FileCopyrightText: Copyright (c) 2019-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 */

#ifndef NVGPU_BOARDOBJGRP_CLASSES_H
#define NVGPU_BOARDOBJGRP_CLASSES_H
/* Enumeration of BOARDOBJGRP class IDs. Used as "classId" argument for
 * communications between Kernel and PMU via the various generic
 * BOARDOBJGRP interfaces.
*/
#define NV_PMU_BOARDOBJGRP_CLASS_ID(_unit, _class)                        \
	NV_PMU_BOARDOBJGRP_CLASS_ID_##_unit##_##_class

// UNIT CLK
#define NV_PMU_CLK_BOARDOBJGRP_CLASS_ID__FIRST (0x1U)
#define NV_PMU_CLK_BOARDOBJGRP_CLASS_ID_CLK_DOMAIN (0x1U)
#define NV_PMU_CLK_BOARDOBJGRP_CLASS_ID_CLK_PROG (0x2U)
#define NV_PMU_CLK_BOARDOBJGRP_CLASS_ID_CLK_ADC_DEVICE (0x3U)
#define NV_PMU_CLK_BOARDOBJGRP_CLASS_ID_CLK_NAFLL_DEVICE (0x4U)
#define NV_PMU_CLK_BOARDOBJGRP_CLASS_ID_CLK_CLK_VF_POINT (0x5U)
#define NV_PMU_CLK_BOARDOBJGRP_CLASS_ID_CLK_CLK_FREQ_CONTROLLER (0x6U)
#define NV_PMU_CLK_BOARDOBJGRP_CLASS_ID_CLK_PLL_DEVICE (0x7U)
#define NV_PMU_CLK_BOARDOBJGRP_CLASS_ID_CLK_FREQ_DOMAIN (0x8U)
#define NV_PMU_CLK_BOARDOBJGRP_CLASS_ID_CLK_CLK_VOLT_CONTROLLER (0x9U)
#define NV_PMU_CLK_BOARDOBJGRP_CLASS_ID_CLK_CLK_ENUM (0xaU)
#define NV_PMU_CLK_BOARDOBJGRP_CLASS_ID_CLK_CLK_VF_REL (0xbU)
#define NV_PMU_CLK_BOARDOBJGRP_CLASS_ID_CLK_CLK_PROP_REGIME (0xcU)
#define NV_PMU_CLK_BOARDOBJGRP_CLASS_ID_CLK_CLK_PROP_TOP (0xdU)
#define NV_PMU_CLK_BOARDOBJGRP_CLASS_ID_CLK_CLK_PROP_TOP_REL (0xeU)
#define NV_PMU_CLK_BOARDOBJGRP_CLASS_ID_CLK_CLIENT_CLK_VF_POINT (0xfU)
#define NV_PMU_CLK_BOARDOBJGRP_CLASS_ID_CLK_CLIENT_CLK_PROP_TOP_POL \
	(0x10U)
#define NV_PMU_CLK_BOARDOBJGRP_CLASS_ID_CLK_CLK_VF_TUPLE (0x11U)
#define NV_PMU_CLK_BOARDOBJGRP_CLASS_ID_CLK__LAST (0x11U)
// UNIT VOLT
#define NV_PMU_VOLT_BOARDOBJGRP_CLASS_ID__FIRST (0x12U)
#define NV_PMU_VOLT_BOARDOBJGRP_CLASS_ID_VOLT_VOLT_RAIL (0x12U)
#define NV_PMU_VOLT_BOARDOBJGRP_CLASS_ID_VOLT_VOLT_DEVICE (0x13U)
#define NV_PMU_VOLT_BOARDOBJGRP_CLASS_ID_VOLT_VOLT_POLICY (0x14U)
#define NV_PMU_VOLT_BOARDOBJGRP_CLASS_ID_VOLT_VOLT_THRESHOLD_CONTROLLER \
	(0x15U)
#define NV_PMU_VOLT_BOARDOBJGRP_CLASS_ID_VOLT__LAST (0x15U)
// UNIT FAN
#define NV_PMU_FAN_BOARDOBJGRP_CLASS_ID__FIRST (0x16U)
#define NV_PMU_FAN_BOARDOBJGRP_CLASS_ID_FAN_FAN_COOLER (0x16U)
#define NV_PMU_FAN_BOARDOBJGRP_CLASS_ID_FAN_FAN_POLICY (0x17U)
#define NV_PMU_FAN_BOARDOBJGRP_CLASS_ID_FAN_FAN_ARBITER (0x18U)
#define NV_PMU_FAN_BOARDOBJGRP_CLASS_ID_FAN__LAST (0x18U)
// UNIT PERF
#define NV_PMU_PERF_BOARDOBJGRP_CLASS_ID__FIRST (0x19U)
#define NV_PMU_PERF_BOARDOBJGRP_CLASS_ID_PERF_VFE_VAR (0x19U)
#define NV_PMU_PERF_BOARDOBJGRP_CLASS_ID_PERF_VFE_EQU (0x1aU)
#define NV_PMU_PERF_BOARDOBJGRP_CLASS_ID_PERF_VPSTATE (0x1bU)
#define NV_PMU_PERF_BOARDOBJGRP_CLASS_ID_PERF_PSTATE (0x1cU)
#define NV_PMU_PERF_BOARDOBJGRP_CLASS_ID_PERF_PERF_LIMIT (0x1dU)
#define NV_PMU_PERF_BOARDOBJGRP_CLASS_ID_PERF_POLICY (0x1eU)
#define NV_PMU_PERF_BOARDOBJGRP_CLASS_ID_PERF_PERF_MODE_CONFIG (0x1fU)
#define NV_PMU_PERF_BOARDOBJGRP_CLASS_ID_PERF_PERF_MODE (0x20U)
#define NV_PMU_PERF_BOARDOBJGRP_CLASS_ID_PERF_PERF_VF_QOS (0x21U)
#define NV_PMU_PERF_BOARDOBJGRP_CLASS_ID_PERF__LAST (0x21U)
// UNIT THERM
#define NV_PMU_THERM_BOARDOBJGRP_CLASS_ID__FIRST (0x22U)
#define NV_PMU_THERM_BOARDOBJGRP_CLASS_ID_THERM_THERM_DEVICE (0x22U)
#define NV_PMU_THERM_BOARDOBJGRP_CLASS_ID_THERM_THERM_CHANNEL (0x23U)
#define NV_PMU_THERM_BOARDOBJGRP_CLASS_ID_THERM_THERM_POLICY (0x24U)
#define NV_PMU_THERM_BOARDOBJGRP_CLASS_ID_THERM_THERM_MONITOR (0x25U)
#define NV_PMU_THERM_BOARDOBJGRP_CLASS_ID_THERM__LAST (0x25U)
// UNIT PMGR
#define NV_PMU_PMGR_BOARDOBJGRP_CLASS_ID__FIRST (0x26U)
#define NV_PMU_PMGR_BOARDOBJGRP_CLASS_ID_PMGR_PWR_EQUATION (0x26U)
#define NV_PMU_PMGR_BOARDOBJGRP_CLASS_ID_PMGR_PWR_DEVICE (0x27U)
#define NV_PMU_PMGR_BOARDOBJGRP_CLASS_ID_PMGR_PWR_CHANNEL (0x28U)
#define NV_PMU_PMGR_BOARDOBJGRP_CLASS_ID_PMGR_PWR_POLICY (0x29U)
#define NV_PMU_PMGR_BOARDOBJGRP_CLASS_ID_PMGR_I2C_DEVICE (0x2aU)
#define NV_PMU_PMGR_BOARDOBJGRP_CLASS_ID_PMGR_ILLUM_DEVICE (0x2bU)
#define NV_PMU_PMGR_BOARDOBJGRP_CLASS_ID_PMGR_ILLUM_ZONE (0x2cU)
#define NV_PMU_PMGR_BOARDOBJGRP_CLASS_ID_PMGR_ISINK_CONTROLLER (0x2dU)
#define NV_PMU_PMGR_BOARDOBJGRP_CLASS_ID_PMGR__LAST (0x2dU)
// UNIT PERF_CF
#define NV_PMU_PERF_CF_BOARDOBJGRP_CLASS_ID__FIRST (0x2eU)
#define NV_PMU_PERF_CF_BOARDOBJGRP_CLASS_ID_PERF_CF_SENSOR (0x2eU)
#define NV_PMU_PERF_CF_BOARDOBJGRP_CLASS_ID_PERF_CF_PM_SENSOR (0x2fU)
#define NV_PMU_PERF_CF_BOARDOBJGRP_CLASS_ID_PERF_CF_TOPOLOGY (0x30U)
#define NV_PMU_PERF_CF_BOARDOBJGRP_CLASS_ID_PERF_CF_CONTROLLER (0x31U)
#define NV_PMU_PERF_CF_BOARDOBJGRP_CLASS_ID_PERF_CF_POLICY (0x32U)
#define NV_PMU_PERF_CF_BOARDOBJGRP_CLASS_ID_PERF_CF_PWR_MODEL (0x33U)
#define NV_PMU_PERF_CF_BOARDOBJGRP_CLASS_ID_PERF_CF_CLIENT_PWR_PROFILE \
	(0x34U)
#define NV_PMU_PERF_CF_BOARDOBJGRP_CLASS_ID_PERF_CF_CLIENT_POLICY \
	(0x35U)
#define NV_PMU_PERF_CF_BOARDOBJGRP_CLASS_ID_PERF_CF_CLIENT_CONTROLLER \
	(0x36U)
#define NV_PMU_PERF_CF_BOARDOBJGRP_CLASS_ID__LAST (0x36U)
// UNIT NNE
#define NV_PMU_NNE_BOARDOBJGRP_CLASS_ID__FIRST (0x37U)
#define NV_PMU_NNE_BOARDOBJGRP_CLASS_ID_NNE_NNE_VAR (0x37U)
#define NV_PMU_NNE_BOARDOBJGRP_CLASS_ID_NNE_NNE_LAYER (0x38U)
#define NV_PMU_NNE_BOARDOBJGRP_CLASS_ID_NNE_NNE_DESC (0x39U)
#define NV_PMU_NNE_BOARDOBJGRP_CLASS_ID__LAST (0x39U)
// UNIT PMU
#define NV_PMU_PMU_BOARDOBJGRP_CLASS_ID__FIRST (0x3aU)
#define NV_PMU_PMU_BOARDOBJGRP_CLASS_ID_PMU_PMU_SUPER_SURFACE (0x3aU)
#define NV_PMU_PMU_BOARDOBJGRP_CLASS_ID_PMU_PMU_SUPER_SURFACE_MEMBER \
	(0x3bU)
#define NV_PMU_PMU_BOARDOBJGRP_CLASS_ID__LAST (0x3cU)

/* Compatibility aliases for legacy code */
// CLK unit aliases
#define NV_PMU_CLK_BOARDOBJGRP_CLASS_ID_CLK_VF_POINT \
	NV_PMU_CLK_BOARDOBJGRP_CLASS_ID_CLK_CLK_VF_POINT
#define NV_PMU_CLK_BOARDOBJGRP_CLASS_ID_CLK_VF_REL \
	NV_PMU_CLK_BOARDOBJGRP_CLASS_ID_CLK_CLK_VF_REL
#define NV_PMU_CLK_BOARDOBJGRP_CLASS_ID_CLK_PROP_TOP \
	NV_PMU_CLK_BOARDOBJGRP_CLASS_ID_CLK_CLK_PROP_TOP
#define NV_PMU_CLK_BOARDOBJGRP_CLASS_ID_CLK_ENUM \
	NV_PMU_CLK_BOARDOBJGRP_CLASS_ID_CLK_CLK_ENUM
#define NV_PMU_CLK_BOARDOBJGRP_CLASS_ID_FLL_DEVICE \
	NV_PMU_CLK_BOARDOBJGRP_CLASS_ID_CLK_NAFLL_DEVICE
#define NV_PMU_CLK_BOARDOBJGRP_CLASS_ID_VIN_DEVICE \
	NV_PMU_CLK_BOARDOBJGRP_CLASS_ID_CLK_ADC_DEVICE

// VOLT unit aliases
#define NV_PMU_VOLT_BOARDOBJGRP_CLASS_ID_VOLT_RAIL \
	NV_PMU_VOLT_BOARDOBJGRP_CLASS_ID_VOLT_VOLT_RAIL
#define NV_PMU_VOLT_BOARDOBJGRP_CLASS_ID_VOLT_DEVICE \
	NV_PMU_VOLT_BOARDOBJGRP_CLASS_ID_VOLT_VOLT_DEVICE
#define NV_PMU_VOLT_BOARDOBJGRP_CLASS_ID_VOLT_POLICY \
	NV_PMU_VOLT_BOARDOBJGRP_CLASS_ID_VOLT_VOLT_POLICY

// PERF unit aliases
#define NV_PMU_PERF_BOARDOBJGRP_CLASS_ID_VFE_VAR \
	NV_PMU_PERF_BOARDOBJGRP_CLASS_ID_PERF_VFE_VAR
#define NV_PMU_PERF_BOARDOBJGRP_CLASS_ID_VFE_EQU \
	NV_PMU_PERF_BOARDOBJGRP_CLASS_ID_PERF_VFE_EQU
#define NV_PMU_PERF_BOARDOBJGRP_CLASS_ID_PSTATE \
	NV_PMU_PERF_BOARDOBJGRP_CLASS_ID_PERF_PSTATE

// THERM unit aliases
#define NV_PMU_THERM_BOARDOBJGRP_CLASS_ID_THERM_DEVICE \
	NV_PMU_THERM_BOARDOBJGRP_CLASS_ID_THERM_THERM_DEVICE
#define NV_PMU_THERM_BOARDOBJGRP_CLASS_ID_THERM_CHANNEL \
	NV_PMU_THERM_BOARDOBJGRP_CLASS_ID_THERM_THERM_CHANNEL

// Add a new UNIT's BOARDOBJGRP Class IDs here...
// Update this when a new unit is added
#define NV_PMU_BOARDOBJGRP_CLASS_ID__MAX \
	(NV_PMU_PMU_BOARDOBJGRP_CLASS_ID__LAST)
#define NV_PMU_BOARDOBJGRP_CLASS_ID_INVALID (NV_U8_MAX)

#endif /* NVGPU_BOARDOBJGRP_CLASSES_H */
