# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2023, NVIDIA CORPORATION.  All rights reserved.

# Empty Makefile
# NOTE: Do not change or add anything in this Makefile.
# The source code and Makefile rules are copied from the
# kernel/nvidia-$soc/drivers/pci/controller/private-soc. This
# file is just place-holder for empty Makefile to avoid any build
# issue when copy is not done from command line and building
# the tree independent of source copy.
