// SPDX-License-Identifier: MIT
/*
 * SPDX-FileCopyrightText: Copyright (c) 2023-2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * This is a generated file. Do not edit.
 *
 * Steps to regenerate:
 *     python3 ip_files_generator.py <soc_chip> <IP_name> [<dir_name>]
 */

#include "th500_nvltx.h"

#include <tegra_hwpm.h>
#include <hal/th500/soc/th500_soc_perfmon_device_index.h>
#include <hal/th500/soc/th500_soc_regops_allowlist.h>
#include <hal/th500/soc/hw/th500_addr_map_soc_hwpm.h>

static struct hwpm_ip_aperture th500_nvltx_inst0_perfmon_element_static_array[
	TH500_HWPM_IP_NVLTX_NUM_PERFMON_PER_INST] = {
	{
		.element_type = HWPM_ELEMENT_PERFMON,
		.aperture_index = 0U,
		.element_index_mask = BIT(0),
		.element_index = 0U,
		.dt_mmio = NULL,
		.name = "perfmon_nvltx0",
		.device_index = TH500_NVLTX0_PERFMON_DEVICE_NODE_INDEX,
		.start_abs_pa = addr_map_rpg_pm_nvltx0_base_r(),
		.end_abs_pa = addr_map_rpg_pm_nvltx0_limit_r(),
		.start_pa = addr_map_rpg_pm_nvltx0_base_r(),
		.end_pa = addr_map_rpg_pm_nvltx0_limit_r(),
		.base_pa = addr_map_rpg_pm_base_r(),
		.alist = th500_perfmon_alist,
		.alist_size = ARRAY_SIZE(th500_perfmon_alist),
		.fake_registers = NULL,
	},
	{
		.element_type = HWPM_ELEMENT_PERFMON,
		.aperture_index = 1U,
		.element_index_mask = BIT(1),
		.element_index = 1U,
		.dt_mmio = NULL,
		.name = "perfmon_nvltx1",
		.device_index = TH500_NVLTX1_PERFMON_DEVICE_NODE_INDEX,
		.start_abs_pa = addr_map_rpg_pm_nvltx1_base_r(),
		.end_abs_pa = addr_map_rpg_pm_nvltx1_limit_r(),
		.start_pa = addr_map_rpg_pm_nvltx1_base_r(),
		.end_pa = addr_map_rpg_pm_nvltx1_limit_r(),
		.base_pa = addr_map_rpg_pm_base_r(),
		.alist = th500_perfmon_alist,
		.alist_size = ARRAY_SIZE(th500_perfmon_alist),
		.fake_registers = NULL,
	},
	{
		.element_type = HWPM_ELEMENT_PERFMON,
		.aperture_index = 2U,
		.element_index_mask = BIT(2),
		.element_index = 2U,
		.dt_mmio = NULL,
		.name = "perfmon_nvltx2",
		.device_index = TH500_NVLTX2_PERFMON_DEVICE_NODE_INDEX,
		.start_abs_pa = addr_map_rpg_pm_nvltx2_base_r(),
		.end_abs_pa = addr_map_rpg_pm_nvltx2_limit_r(),
		.start_pa = addr_map_rpg_pm_nvltx2_base_r(),
		.end_pa = addr_map_rpg_pm_nvltx2_limit_r(),
		.base_pa = addr_map_rpg_pm_base_r(),
		.alist = th500_perfmon_alist,
		.alist_size = ARRAY_SIZE(th500_perfmon_alist),
		.fake_registers = NULL,
	},
	{
		.element_type = HWPM_ELEMENT_PERFMON,
		.aperture_index = 3U,
		.element_index_mask = BIT(3),
		.element_index = 3U,
		.dt_mmio = NULL,
		.name = "perfmon_nvltx3",
		.device_index = TH500_NVLTX3_PERFMON_DEVICE_NODE_INDEX,
		.start_abs_pa = addr_map_rpg_pm_nvltx3_base_r(),
		.end_abs_pa = addr_map_rpg_pm_nvltx3_limit_r(),
		.start_pa = addr_map_rpg_pm_nvltx3_base_r(),
		.end_pa = addr_map_rpg_pm_nvltx3_limit_r(),
		.base_pa = addr_map_rpg_pm_base_r(),
		.alist = th500_perfmon_alist,
		.alist_size = ARRAY_SIZE(th500_perfmon_alist),
		.fake_registers = NULL,
	},
	{
		.element_type = HWPM_ELEMENT_PERFMON,
		.aperture_index = 4U,
		.element_index_mask = BIT(4),
		.element_index = 4U,
		.dt_mmio = NULL,
		.name = "perfmon_nvltx4",
		.device_index = TH500_NVLTX4_PERFMON_DEVICE_NODE_INDEX,
		.start_abs_pa = addr_map_rpg_pm_nvltx4_base_r(),
		.end_abs_pa = addr_map_rpg_pm_nvltx4_limit_r(),
		.start_pa = addr_map_rpg_pm_nvltx4_base_r(),
		.end_pa = addr_map_rpg_pm_nvltx4_limit_r(),
		.base_pa = addr_map_rpg_pm_base_r(),
		.alist = th500_perfmon_alist,
		.alist_size = ARRAY_SIZE(th500_perfmon_alist),
		.fake_registers = NULL,
	},
	{
		.element_type = HWPM_ELEMENT_PERFMON,
		.aperture_index = 5U,
		.element_index_mask = BIT(5),
		.element_index = 5U,
		.dt_mmio = NULL,
		.name = "perfmon_nvltx5",
		.device_index = TH500_NVLTX5_PERFMON_DEVICE_NODE_INDEX,
		.start_abs_pa = addr_map_rpg_pm_nvltx5_base_r(),
		.end_abs_pa = addr_map_rpg_pm_nvltx5_limit_r(),
		.start_pa = addr_map_rpg_pm_nvltx5_base_r(),
		.end_pa = addr_map_rpg_pm_nvltx5_limit_r(),
		.base_pa = addr_map_rpg_pm_base_r(),
		.alist = th500_perfmon_alist,
		.alist_size = ARRAY_SIZE(th500_perfmon_alist),
		.fake_registers = NULL,
	},
	{
		.element_type = HWPM_ELEMENT_PERFMON,
		.aperture_index = 6U,
		.element_index_mask = BIT(6),
		.element_index = 6U,
		.dt_mmio = NULL,
		.name = "perfmon_nvltx6",
		.device_index = TH500_NVLTX6_PERFMON_DEVICE_NODE_INDEX,
		.start_abs_pa = addr_map_rpg_pm_nvltx6_base_r(),
		.end_abs_pa = addr_map_rpg_pm_nvltx6_limit_r(),
		.start_pa = addr_map_rpg_pm_nvltx6_base_r(),
		.end_pa = addr_map_rpg_pm_nvltx6_limit_r(),
		.base_pa = addr_map_rpg_pm_base_r(),
		.alist = th500_perfmon_alist,
		.alist_size = ARRAY_SIZE(th500_perfmon_alist),
		.fake_registers = NULL,
	},
	{
		.element_type = HWPM_ELEMENT_PERFMON,
		.aperture_index = 7U,
		.element_index_mask = BIT(7),
		.element_index = 7U,
		.dt_mmio = NULL,
		.name = "perfmon_nvltx7",
		.device_index = TH500_NVLTX7_PERFMON_DEVICE_NODE_INDEX,
		.start_abs_pa = addr_map_rpg_pm_nvltx7_base_r(),
		.end_abs_pa = addr_map_rpg_pm_nvltx7_limit_r(),
		.start_pa = addr_map_rpg_pm_nvltx7_base_r(),
		.end_pa = addr_map_rpg_pm_nvltx7_limit_r(),
		.base_pa = addr_map_rpg_pm_base_r(),
		.alist = th500_perfmon_alist,
		.alist_size = ARRAY_SIZE(th500_perfmon_alist),
		.fake_registers = NULL,
	},
	{
		.element_type = HWPM_ELEMENT_PERFMON,
		.aperture_index = 8U,
		.element_index_mask = BIT(8),
		.element_index = 8U,
		.dt_mmio = NULL,
		.name = "perfmon_nvltx8",
		.device_index = TH500_NVLTX8_PERFMON_DEVICE_NODE_INDEX,
		.start_abs_pa = addr_map_rpg_pm_nvltx8_base_r(),
		.end_abs_pa = addr_map_rpg_pm_nvltx8_limit_r(),
		.start_pa = addr_map_rpg_pm_nvltx8_base_r(),
		.end_pa = addr_map_rpg_pm_nvltx8_limit_r(),
		.base_pa = addr_map_rpg_pm_base_r(),
		.alist = th500_perfmon_alist,
		.alist_size = ARRAY_SIZE(th500_perfmon_alist),
		.fake_registers = NULL,
	},
	{
		.element_type = HWPM_ELEMENT_PERFMON,
		.aperture_index = 9U,
		.element_index_mask = BIT(9),
		.element_index = 9U,
		.dt_mmio = NULL,
		.name = "perfmon_nvltx9",
		.device_index = TH500_NVLTX9_PERFMON_DEVICE_NODE_INDEX,
		.start_abs_pa = addr_map_rpg_pm_nvltx9_base_r(),
		.end_abs_pa = addr_map_rpg_pm_nvltx9_limit_r(),
		.start_pa = addr_map_rpg_pm_nvltx9_base_r(),
		.end_pa = addr_map_rpg_pm_nvltx9_limit_r(),
		.base_pa = addr_map_rpg_pm_base_r(),
		.alist = th500_perfmon_alist,
		.alist_size = ARRAY_SIZE(th500_perfmon_alist),
		.fake_registers = NULL,
	},
	{
		.element_type = HWPM_ELEMENT_PERFMON,
		.aperture_index = 10U,
		.element_index_mask = BIT(10),
		.element_index = 10U,
		.dt_mmio = NULL,
		.name = "perfmon_nvltx10",
		.device_index = TH500_NVLTX10_PERFMON_DEVICE_NODE_INDEX,
		.start_abs_pa = addr_map_rpg_pm_nvltx10_base_r(),
		.end_abs_pa = addr_map_rpg_pm_nvltx10_limit_r(),
		.start_pa = addr_map_rpg_pm_nvltx10_base_r(),
		.end_pa = addr_map_rpg_pm_nvltx10_limit_r(),
		.base_pa = addr_map_rpg_pm_base_r(),
		.alist = th500_perfmon_alist,
		.alist_size = ARRAY_SIZE(th500_perfmon_alist),
		.fake_registers = NULL,
	},
	{
		.element_type = HWPM_ELEMENT_PERFMON,
		.aperture_index = 11U,
		.element_index_mask = BIT(11),
		.element_index = 11U,
		.dt_mmio = NULL,
		.name = "perfmon_nvltx11",
		.device_index = TH500_NVLTX11_PERFMON_DEVICE_NODE_INDEX,
		.start_abs_pa = addr_map_rpg_pm_nvltx11_base_r(),
		.end_abs_pa = addr_map_rpg_pm_nvltx11_limit_r(),
		.start_pa = addr_map_rpg_pm_nvltx11_base_r(),
		.end_pa = addr_map_rpg_pm_nvltx11_limit_r(),
		.base_pa = addr_map_rpg_pm_base_r(),
		.alist = th500_perfmon_alist,
		.alist_size = ARRAY_SIZE(th500_perfmon_alist),
		.fake_registers = NULL,
	},
};

static struct hwpm_ip_aperture th500_nvltx_inst1_perfmon_element_static_array[
	TH500_HWPM_IP_NVLTX_NUM_PERFMON_PER_INST] = {
	{
		.element_type = HWPM_ELEMENT_PERFMON,
		.aperture_index = 0U,
		.element_index_mask = BIT(0),
		.element_index = 0U,
		.dt_mmio = NULL,
		.name = "perfmon_nvltx0",
		.device_index = TH500_NVLTX0_PERFMON_DEVICE_NODE_INDEX,
		.start_abs_pa = addr_map_rpg_pm_nvltx0_base_r(),
		.end_abs_pa = addr_map_rpg_pm_nvltx0_limit_r(),
		.start_pa = addr_map_rpg_pm_nvltx0_base_r(),
		.end_pa = addr_map_rpg_pm_nvltx0_limit_r(),
		.base_pa = addr_map_rpg_pm_base_r(),
		.alist = th500_perfmon_alist,
		.alist_size = ARRAY_SIZE(th500_perfmon_alist),
		.fake_registers = NULL,
	},
	{
		.element_type = HWPM_ELEMENT_PERFMON,
		.aperture_index = 1U,
		.element_index_mask = BIT(1),
		.element_index = 1U,
		.dt_mmio = NULL,
		.name = "perfmon_nvltx1",
		.device_index = TH500_NVLTX1_PERFMON_DEVICE_NODE_INDEX,
		.start_abs_pa = addr_map_rpg_pm_nvltx1_base_r(),
		.end_abs_pa = addr_map_rpg_pm_nvltx1_limit_r(),
		.start_pa = addr_map_rpg_pm_nvltx1_base_r(),
		.end_pa = addr_map_rpg_pm_nvltx1_limit_r(),
		.base_pa = addr_map_rpg_pm_base_r(),
		.alist = th500_perfmon_alist,
		.alist_size = ARRAY_SIZE(th500_perfmon_alist),
		.fake_registers = NULL,
	},
	{
		.element_type = HWPM_ELEMENT_PERFMON,
		.aperture_index = 2U,
		.element_index_mask = BIT(2),
		.element_index = 2U,
		.dt_mmio = NULL,
		.name = "perfmon_nvltx2",
		.device_index = TH500_NVLTX2_PERFMON_DEVICE_NODE_INDEX,
		.start_abs_pa = addr_map_rpg_pm_nvltx2_base_r(),
		.end_abs_pa = addr_map_rpg_pm_nvltx2_limit_r(),
		.start_pa = addr_map_rpg_pm_nvltx2_base_r(),
		.end_pa = addr_map_rpg_pm_nvltx2_limit_r(),
		.base_pa = addr_map_rpg_pm_base_r(),
		.alist = th500_perfmon_alist,
		.alist_size = ARRAY_SIZE(th500_perfmon_alist),
		.fake_registers = NULL,
	},
	{
		.element_type = HWPM_ELEMENT_PERFMON,
		.aperture_index = 3U,
		.element_index_mask = BIT(3),
		.element_index = 3U,
		.dt_mmio = NULL,
		.name = "perfmon_nvltx3",
		.device_index = TH500_NVLTX3_PERFMON_DEVICE_NODE_INDEX,
		.start_abs_pa = addr_map_rpg_pm_nvltx3_base_r(),
		.end_abs_pa = addr_map_rpg_pm_nvltx3_limit_r(),
		.start_pa = addr_map_rpg_pm_nvltx3_base_r(),
		.end_pa = addr_map_rpg_pm_nvltx3_limit_r(),
		.base_pa = addr_map_rpg_pm_base_r(),
		.alist = th500_perfmon_alist,
		.alist_size = ARRAY_SIZE(th500_perfmon_alist),
		.fake_registers = NULL,
	},
	{
		.element_type = HWPM_ELEMENT_PERFMON,
		.aperture_index = 4U,
		.element_index_mask = BIT(4),
		.element_index = 4U,
		.dt_mmio = NULL,
		.name = "perfmon_nvltx4",
		.device_index = TH500_NVLTX4_PERFMON_DEVICE_NODE_INDEX,
		.start_abs_pa = addr_map_rpg_pm_nvltx4_base_r(),
		.end_abs_pa = addr_map_rpg_pm_nvltx4_limit_r(),
		.start_pa = addr_map_rpg_pm_nvltx4_base_r(),
		.end_pa = addr_map_rpg_pm_nvltx4_limit_r(),
		.base_pa = addr_map_rpg_pm_base_r(),
		.alist = th500_perfmon_alist,
		.alist_size = ARRAY_SIZE(th500_perfmon_alist),
		.fake_registers = NULL,
	},
	{
		.element_type = HWPM_ELEMENT_PERFMON,
		.aperture_index = 5U,
		.element_index_mask = BIT(5),
		.element_index = 5U,
		.dt_mmio = NULL,
		.name = "perfmon_nvltx5",
		.device_index = TH500_NVLTX5_PERFMON_DEVICE_NODE_INDEX,
		.start_abs_pa = addr_map_rpg_pm_nvltx5_base_r(),
		.end_abs_pa = addr_map_rpg_pm_nvltx5_limit_r(),
		.start_pa = addr_map_rpg_pm_nvltx5_base_r(),
		.end_pa = addr_map_rpg_pm_nvltx5_limit_r(),
		.base_pa = addr_map_rpg_pm_base_r(),
		.alist = th500_perfmon_alist,
		.alist_size = ARRAY_SIZE(th500_perfmon_alist),
		.fake_registers = NULL,
	},
	{
		.element_type = HWPM_ELEMENT_PERFMON,
		.aperture_index = 6U,
		.element_index_mask = BIT(6),
		.element_index = 6U,
		.dt_mmio = NULL,
		.name = "perfmon_nvltx6",
		.device_index = TH500_NVLTX6_PERFMON_DEVICE_NODE_INDEX,
		.start_abs_pa = addr_map_rpg_pm_nvltx6_base_r(),
		.end_abs_pa = addr_map_rpg_pm_nvltx6_limit_r(),
		.start_pa = addr_map_rpg_pm_nvltx6_base_r(),
		.end_pa = addr_map_rpg_pm_nvltx6_limit_r(),
		.base_pa = addr_map_rpg_pm_base_r(),
		.alist = th500_perfmon_alist,
		.alist_size = ARRAY_SIZE(th500_perfmon_alist),
		.fake_registers = NULL,
	},
	{
		.element_type = HWPM_ELEMENT_PERFMON,
		.aperture_index = 7U,
		.element_index_mask = BIT(7),
		.element_index = 7U,
		.dt_mmio = NULL,
		.name = "perfmon_nvltx7",
		.device_index = TH500_NVLTX7_PERFMON_DEVICE_NODE_INDEX,
		.start_abs_pa = addr_map_rpg_pm_nvltx7_base_r(),
		.end_abs_pa = addr_map_rpg_pm_nvltx7_limit_r(),
		.start_pa = addr_map_rpg_pm_nvltx7_base_r(),
		.end_pa = addr_map_rpg_pm_nvltx7_limit_r(),
		.base_pa = addr_map_rpg_pm_base_r(),
		.alist = th500_perfmon_alist,
		.alist_size = ARRAY_SIZE(th500_perfmon_alist),
		.fake_registers = NULL,
	},
	{
		.element_type = HWPM_ELEMENT_PERFMON,
		.aperture_index = 8U,
		.element_index_mask = BIT(8),
		.element_index = 8U,
		.dt_mmio = NULL,
		.name = "perfmon_nvltx8",
		.device_index = TH500_NVLTX8_PERFMON_DEVICE_NODE_INDEX,
		.start_abs_pa = addr_map_rpg_pm_nvltx8_base_r(),
		.end_abs_pa = addr_map_rpg_pm_nvltx8_limit_r(),
		.start_pa = addr_map_rpg_pm_nvltx8_base_r(),
		.end_pa = addr_map_rpg_pm_nvltx8_limit_r(),
		.base_pa = addr_map_rpg_pm_base_r(),
		.alist = th500_perfmon_alist,
		.alist_size = ARRAY_SIZE(th500_perfmon_alist),
		.fake_registers = NULL,
	},
	{
		.element_type = HWPM_ELEMENT_PERFMON,
		.aperture_index = 9U,
		.element_index_mask = BIT(9),
		.element_index = 9U,
		.dt_mmio = NULL,
		.name = "perfmon_nvltx9",
		.device_index = TH500_NVLTX9_PERFMON_DEVICE_NODE_INDEX,
		.start_abs_pa = addr_map_rpg_pm_nvltx9_base_r(),
		.end_abs_pa = addr_map_rpg_pm_nvltx9_limit_r(),
		.start_pa = addr_map_rpg_pm_nvltx9_base_r(),
		.end_pa = addr_map_rpg_pm_nvltx9_limit_r(),
		.base_pa = addr_map_rpg_pm_base_r(),
		.alist = th500_perfmon_alist,
		.alist_size = ARRAY_SIZE(th500_perfmon_alist),
		.fake_registers = NULL,
	},
	{
		.element_type = HWPM_ELEMENT_PERFMON,
		.aperture_index = 10U,
		.element_index_mask = BIT(10),
		.element_index = 10U,
		.dt_mmio = NULL,
		.name = "perfmon_nvltx10",
		.device_index = TH500_NVLTX10_PERFMON_DEVICE_NODE_INDEX,
		.start_abs_pa = addr_map_rpg_pm_nvltx10_base_r(),
		.end_abs_pa = addr_map_rpg_pm_nvltx10_limit_r(),
		.start_pa = addr_map_rpg_pm_nvltx10_base_r(),
		.end_pa = addr_map_rpg_pm_nvltx10_limit_r(),
		.base_pa = addr_map_rpg_pm_base_r(),
		.alist = th500_perfmon_alist,
		.alist_size = ARRAY_SIZE(th500_perfmon_alist),
		.fake_registers = NULL,
	},
	{
		.element_type = HWPM_ELEMENT_PERFMON,
		.aperture_index = 11U,
		.element_index_mask = BIT(11),
		.element_index = 11U,
		.dt_mmio = NULL,
		.name = "perfmon_nvltx11",
		.device_index = TH500_NVLTX11_PERFMON_DEVICE_NODE_INDEX,
		.start_abs_pa = addr_map_rpg_pm_nvltx11_base_r(),
		.end_abs_pa = addr_map_rpg_pm_nvltx11_limit_r(),
		.start_pa = addr_map_rpg_pm_nvltx11_base_r(),
		.end_pa = addr_map_rpg_pm_nvltx11_limit_r(),
		.base_pa = addr_map_rpg_pm_base_r(),
		.alist = th500_perfmon_alist,
		.alist_size = ARRAY_SIZE(th500_perfmon_alist),
		.fake_registers = NULL,
	},
};

static struct hwpm_ip_aperture th500_nvltx_inst0_perfmux_element_static_array[
	TH500_HWPM_IP_NVLTX_NUM_PERFMUX_PER_INST] = {
	{
		.element_type = IP_ELEMENT_PERFMUX,
		.aperture_index = 0U,
		.element_index_mask = BIT(0),
		.element_index = 0U,
		.dt_mmio = NULL,
		.name = {'\0'},
		.start_abs_pa = addr_map_nvlw0_nvldl0_base_r(),
		.end_abs_pa = addr_map_nvlw0_nvldl0_limit_r(),
		.start_pa = addr_map_nvlw0_nvldl0_base_r(),
		.end_pa = addr_map_nvlw0_nvldl0_limit_r(),
		.base_pa = 0ULL,
		.alist = th500_nvltx_alist,
		.alist_size = ARRAY_SIZE(th500_nvltx_alist),
		.fake_registers = NULL,
	},
	{
		.element_type = IP_ELEMENT_PERFMUX,
		.aperture_index = 1U,
		.element_index_mask = BIT(1),
		.element_index = 1U,
		.dt_mmio = NULL,
		.name = {'\0'},
		.start_abs_pa = addr_map_nvlw0_nvltlc0_base_r(),
		.end_abs_pa = addr_map_nvlw0_nvltlc0_limit_r(),
		.start_pa = addr_map_nvlw0_nvltlc0_base_r(),
		.end_pa = addr_map_nvlw0_nvltlc0_limit_r(),
		.base_pa = 0ULL,
		.alist = th500_nvltx_alist,
		.alist_size = ARRAY_SIZE(th500_nvltx_alist),
		.fake_registers = NULL,
	},
	{
		.element_type = IP_ELEMENT_PERFMUX,
		.aperture_index = 2U,
		.element_index_mask = BIT(2),
		.element_index = 2U,
		.dt_mmio = NULL,
		.name = {'\0'},
		.start_abs_pa = addr_map_nvlw0_nvldl1_base_r(),
		.end_abs_pa = addr_map_nvlw0_nvldl1_limit_r(),
		.start_pa = addr_map_nvlw0_nvldl1_base_r(),
		.end_pa = addr_map_nvlw0_nvldl1_limit_r(),
		.base_pa = 0ULL,
		.alist = th500_nvltx_alist,
		.alist_size = ARRAY_SIZE(th500_nvltx_alist),
		.fake_registers = NULL,
	},
	{
		.element_type = IP_ELEMENT_PERFMUX,
		.aperture_index = 3U,
		.element_index_mask = BIT(3),
		.element_index = 3U,
		.dt_mmio = NULL,
		.name = {'\0'},
		.start_abs_pa = addr_map_nvlw0_nvltlc1_base_r(),
		.end_abs_pa = addr_map_nvlw0_nvltlc1_limit_r(),
		.start_pa = addr_map_nvlw0_nvltlc1_base_r(),
		.end_pa = addr_map_nvlw0_nvltlc1_limit_r(),
		.base_pa = 0ULL,
		.alist = th500_nvltx_alist,
		.alist_size = ARRAY_SIZE(th500_nvltx_alist),
		.fake_registers = NULL,
	},
	{
		.element_type = IP_ELEMENT_PERFMUX,
		.aperture_index = 4U,
		.element_index_mask = BIT(4),
		.element_index = 4U,
		.dt_mmio = NULL,
		.name = {'\0'},
		.start_abs_pa = addr_map_nvlw0_nvldl2_base_r(),
		.end_abs_pa = addr_map_nvlw0_nvldl2_limit_r(),
		.start_pa = addr_map_nvlw0_nvldl2_base_r(),
		.end_pa = addr_map_nvlw0_nvldl2_limit_r(),
		.base_pa = 0ULL,
		.alist = th500_nvltx_alist,
		.alist_size = ARRAY_SIZE(th500_nvltx_alist),
		.fake_registers = NULL,
	},
	{
		.element_type = IP_ELEMENT_PERFMUX,
		.aperture_index = 5U,
		.element_index_mask = BIT(5),
		.element_index = 5U,
		.dt_mmio = NULL,
		.name = {'\0'},
		.start_abs_pa = addr_map_nvlw0_nvltlc2_base_r(),
		.end_abs_pa = addr_map_nvlw0_nvltlc2_limit_r(),
		.start_pa = addr_map_nvlw0_nvltlc2_base_r(),
		.end_pa = addr_map_nvlw0_nvltlc2_limit_r(),
		.base_pa = 0ULL,
		.alist = th500_nvltx_alist,
		.alist_size = ARRAY_SIZE(th500_nvltx_alist),
		.fake_registers = NULL,
	},
	{
		.element_type = IP_ELEMENT_PERFMUX,
		.aperture_index = 6U,
		.element_index_mask = BIT(6),
		.element_index = 6U,
		.dt_mmio = NULL,
		.name = {'\0'},
		.start_abs_pa = addr_map_nvlw0_nvldl3_base_r(),
		.end_abs_pa = addr_map_nvlw0_nvldl3_limit_r(),
		.start_pa = addr_map_nvlw0_nvldl3_base_r(),
		.end_pa = addr_map_nvlw0_nvldl3_limit_r(),
		.base_pa = 0ULL,
		.alist = th500_nvltx_alist,
		.alist_size = ARRAY_SIZE(th500_nvltx_alist),
		.fake_registers = NULL,
	},
	{
		.element_type = IP_ELEMENT_PERFMUX,
		.aperture_index = 7U,
		.element_index_mask = BIT(7),
		.element_index = 7U,
		.dt_mmio = NULL,
		.name = {'\0'},
		.start_abs_pa = addr_map_nvlw0_nvltlc3_base_r(),
		.end_abs_pa = addr_map_nvlw0_nvltlc3_limit_r(),
		.start_pa = addr_map_nvlw0_nvltlc3_base_r(),
		.end_pa = addr_map_nvlw0_nvltlc3_limit_r(),
		.base_pa = 0ULL,
		.alist = th500_nvltx_alist,
		.alist_size = ARRAY_SIZE(th500_nvltx_alist),
		.fake_registers = NULL,
	},
	{
		.element_type = IP_ELEMENT_PERFMUX,
		.aperture_index = 8U,
		.element_index_mask = BIT(8),
		.element_index = 8U,
		.dt_mmio = NULL,
		.name = {'\0'},
		.start_abs_pa = addr_map_nvlw0_nvldl4_base_r(),
		.end_abs_pa = addr_map_nvlw0_nvldl4_limit_r(),
		.start_pa = addr_map_nvlw0_nvldl4_base_r(),
		.end_pa = addr_map_nvlw0_nvldl4_limit_r(),
		.base_pa = 0ULL,
		.alist = th500_nvltx_alist,
		.alist_size = ARRAY_SIZE(th500_nvltx_alist),
		.fake_registers = NULL,
	},
	{
		.element_type = IP_ELEMENT_PERFMUX,
		.aperture_index = 9U,
		.element_index_mask = BIT(9),
		.element_index = 9U,
		.dt_mmio = NULL,
		.name = {'\0'},
		.start_abs_pa = addr_map_nvlw0_nvltlc4_base_r(),
		.end_abs_pa = addr_map_nvlw0_nvltlc4_limit_r(),
		.start_pa = addr_map_nvlw0_nvltlc4_base_r(),
		.end_pa = addr_map_nvlw0_nvltlc4_limit_r(),
		.base_pa = 0ULL,
		.alist = th500_nvltx_alist,
		.alist_size = ARRAY_SIZE(th500_nvltx_alist),
		.fake_registers = NULL,
	},
	{
		.element_type = IP_ELEMENT_PERFMUX,
		.aperture_index = 10U,
		.element_index_mask = BIT(10),
		.element_index = 10U,
		.dt_mmio = NULL,
		.name = {'\0'},
		.start_abs_pa = addr_map_nvlw0_nvldl5_base_r(),
		.end_abs_pa = addr_map_nvlw0_nvldl5_limit_r(),
		.start_pa = addr_map_nvlw0_nvldl5_base_r(),
		.end_pa = addr_map_nvlw0_nvldl5_limit_r(),
		.base_pa = 0ULL,
		.alist = th500_nvltx_alist,
		.alist_size = ARRAY_SIZE(th500_nvltx_alist),
		.fake_registers = NULL,
	},
	{
		.element_type = IP_ELEMENT_PERFMUX,
		.aperture_index = 11U,
		.element_index_mask = BIT(11),
		.element_index = 11U,
		.dt_mmio = NULL,
		.name = {'\0'},
		.start_abs_pa = addr_map_nvlw0_nvltlc5_base_r(),
		.end_abs_pa = addr_map_nvlw0_nvltlc5_limit_r(),
		.start_pa = addr_map_nvlw0_nvltlc5_base_r(),
		.end_pa = addr_map_nvlw0_nvltlc5_limit_r(),
		.base_pa = 0ULL,
		.alist = th500_nvltx_alist,
		.alist_size = ARRAY_SIZE(th500_nvltx_alist),
		.fake_registers = NULL,
	},
};

static struct hwpm_ip_aperture th500_nvltx_inst1_perfmux_element_static_array[
	TH500_HWPM_IP_NVLTX_NUM_PERFMUX_PER_INST] = {
	{
		.element_type = IP_ELEMENT_PERFMUX,
		.aperture_index = 0U,
		.element_index_mask = BIT(0),
		.element_index = 0U,
		.dt_mmio = NULL,
		.name = {'\0'},
		.start_abs_pa = addr_map_nvlw1_nvldl0_base_r(),
		.end_abs_pa = addr_map_nvlw1_nvldl0_limit_r(),
		.start_pa = addr_map_nvlw1_nvldl0_base_r(),
		.end_pa = addr_map_nvlw1_nvldl0_limit_r(),
		.base_pa = 0ULL,
		.alist = th500_nvltx_alist,
		.alist_size = ARRAY_SIZE(th500_nvltx_alist),
		.fake_registers = NULL,
	},
	{
		.element_type = IP_ELEMENT_PERFMUX,
		.aperture_index = 1U,
		.element_index_mask = BIT(1),
		.element_index = 1U,
		.dt_mmio = NULL,
		.name = {'\0'},
		.start_abs_pa = addr_map_nvlw1_nvltlc0_base_r(),
		.end_abs_pa = addr_map_nvlw1_nvltlc0_limit_r(),
		.start_pa = addr_map_nvlw1_nvltlc0_base_r(),
		.end_pa = addr_map_nvlw1_nvltlc0_limit_r(),
		.base_pa = 0ULL,
		.alist = th500_nvltx_alist,
		.alist_size = ARRAY_SIZE(th500_nvltx_alist),
		.fake_registers = NULL,
	},
	{
		.element_type = IP_ELEMENT_PERFMUX,
		.aperture_index = 2U,
		.element_index_mask = BIT(2),
		.element_index = 2U,
		.dt_mmio = NULL,
		.name = {'\0'},
		.start_abs_pa = addr_map_nvlw1_nvldl1_base_r(),
		.end_abs_pa = addr_map_nvlw1_nvldl1_limit_r(),
		.start_pa = addr_map_nvlw1_nvldl1_base_r(),
		.end_pa = addr_map_nvlw1_nvldl1_limit_r(),
		.base_pa = 0ULL,
		.alist = th500_nvltx_alist,
		.alist_size = ARRAY_SIZE(th500_nvltx_alist),
		.fake_registers = NULL,
	},
	{
		.element_type = IP_ELEMENT_PERFMUX,
		.aperture_index = 3U,
		.element_index_mask = BIT(3),
		.element_index = 3U,
		.dt_mmio = NULL,
		.name = {'\0'},
		.start_abs_pa = addr_map_nvlw1_nvltlc1_base_r(),
		.end_abs_pa = addr_map_nvlw1_nvltlc1_limit_r(),
		.start_pa = addr_map_nvlw1_nvltlc1_base_r(),
		.end_pa = addr_map_nvlw1_nvltlc1_limit_r(),
		.base_pa = 0ULL,
		.alist = th500_nvltx_alist,
		.alist_size = ARRAY_SIZE(th500_nvltx_alist),
		.fake_registers = NULL,
	},
	{
		.element_type = IP_ELEMENT_PERFMUX,
		.aperture_index = 4U,
		.element_index_mask = BIT(4),
		.element_index = 4U,
		.dt_mmio = NULL,
		.name = {'\0'},
		.start_abs_pa = addr_map_nvlw1_nvldl2_base_r(),
		.end_abs_pa = addr_map_nvlw1_nvldl2_limit_r(),
		.start_pa = addr_map_nvlw1_nvldl2_base_r(),
		.end_pa = addr_map_nvlw1_nvldl2_limit_r(),
		.base_pa = 0ULL,
		.alist = th500_nvltx_alist,
		.alist_size = ARRAY_SIZE(th500_nvltx_alist),
		.fake_registers = NULL,
	},
	{
		.element_type = IP_ELEMENT_PERFMUX,
		.aperture_index = 5U,
		.element_index_mask = BIT(5),
		.element_index = 5U,
		.dt_mmio = NULL,
		.name = {'\0'},
		.start_abs_pa = addr_map_nvlw1_nvltlc2_base_r(),
		.end_abs_pa = addr_map_nvlw1_nvltlc2_limit_r(),
		.start_pa = addr_map_nvlw1_nvltlc2_base_r(),
		.end_pa = addr_map_nvlw1_nvltlc2_limit_r(),
		.base_pa = 0ULL,
		.alist = th500_nvltx_alist,
		.alist_size = ARRAY_SIZE(th500_nvltx_alist),
		.fake_registers = NULL,
	},
	{
		.element_type = IP_ELEMENT_PERFMUX,
		.aperture_index = 6U,
		.element_index_mask = BIT(6),
		.element_index = 6U,
		.dt_mmio = NULL,
		.name = {'\0'},
		.start_abs_pa = addr_map_nvlw1_nvldl3_base_r(),
		.end_abs_pa = addr_map_nvlw1_nvldl3_limit_r(),
		.start_pa = addr_map_nvlw1_nvldl3_base_r(),
		.end_pa = addr_map_nvlw1_nvldl3_limit_r(),
		.base_pa = 0ULL,
		.alist = th500_nvltx_alist,
		.alist_size = ARRAY_SIZE(th500_nvltx_alist),
		.fake_registers = NULL,
	},
	{
		.element_type = IP_ELEMENT_PERFMUX,
		.aperture_index = 7U,
		.element_index_mask = BIT(7),
		.element_index = 7U,
		.dt_mmio = NULL,
		.name = {'\0'},
		.start_abs_pa = addr_map_nvlw1_nvltlc3_base_r(),
		.end_abs_pa = addr_map_nvlw1_nvltlc3_limit_r(),
		.start_pa = addr_map_nvlw1_nvltlc3_base_r(),
		.end_pa = addr_map_nvlw1_nvltlc3_limit_r(),
		.base_pa = 0ULL,
		.alist = th500_nvltx_alist,
		.alist_size = ARRAY_SIZE(th500_nvltx_alist),
		.fake_registers = NULL,
	},
	{
		.element_type = IP_ELEMENT_PERFMUX,
		.aperture_index = 8U,
		.element_index_mask = BIT(8),
		.element_index = 8U,
		.dt_mmio = NULL,
		.name = {'\0'},
		.start_abs_pa = addr_map_nvlw1_nvldl4_base_r(),
		.end_abs_pa = addr_map_nvlw1_nvldl4_limit_r(),
		.start_pa = addr_map_nvlw1_nvldl4_base_r(),
		.end_pa = addr_map_nvlw1_nvldl4_limit_r(),
		.base_pa = 0ULL,
		.alist = th500_nvltx_alist,
		.alist_size = ARRAY_SIZE(th500_nvltx_alist),
		.fake_registers = NULL,
	},
	{
		.element_type = IP_ELEMENT_PERFMUX,
		.aperture_index = 9U,
		.element_index_mask = BIT(9),
		.element_index = 9U,
		.dt_mmio = NULL,
		.name = {'\0'},
		.start_abs_pa = addr_map_nvlw1_nvltlc4_base_r(),
		.end_abs_pa = addr_map_nvlw1_nvltlc4_limit_r(),
		.start_pa = addr_map_nvlw1_nvltlc4_base_r(),
		.end_pa = addr_map_nvlw1_nvltlc4_limit_r(),
		.base_pa = 0ULL,
		.alist = th500_nvltx_alist,
		.alist_size = ARRAY_SIZE(th500_nvltx_alist),
		.fake_registers = NULL,
	},
	{
		.element_type = IP_ELEMENT_PERFMUX,
		.aperture_index = 10U,
		.element_index_mask = BIT(10),
		.element_index = 10U,
		.dt_mmio = NULL,
		.name = {'\0'},
		.start_abs_pa = addr_map_nvlw1_nvldl5_base_r(),
		.end_abs_pa = addr_map_nvlw1_nvldl5_limit_r(),
		.start_pa = addr_map_nvlw1_nvldl5_base_r(),
		.end_pa = addr_map_nvlw1_nvldl5_limit_r(),
		.base_pa = 0ULL,
		.alist = th500_nvltx_alist,
		.alist_size = ARRAY_SIZE(th500_nvltx_alist),
		.fake_registers = NULL,
	},
	{
		.element_type = IP_ELEMENT_PERFMUX,
		.aperture_index = 11U,
		.element_index_mask = BIT(11),
		.element_index = 11U,
		.dt_mmio = NULL,
		.name = {'\0'},
		.start_abs_pa = addr_map_nvlw1_nvltlc5_base_r(),
		.end_abs_pa = addr_map_nvlw1_nvltlc5_limit_r(),
		.start_pa = addr_map_nvlw1_nvltlc5_base_r(),
		.end_pa = addr_map_nvlw1_nvltlc5_limit_r(),
		.base_pa = 0ULL,
		.alist = th500_nvltx_alist,
		.alist_size = ARRAY_SIZE(th500_nvltx_alist),
		.fake_registers = NULL,
	},
};

static struct hwpm_ip_aperture th500_nvltx_inst0_broadcast_element_static_array[
	TH500_HWPM_IP_NVLTX_NUM_BROADCAST_PER_INST] = {
	{
		.element_type = IP_ELEMENT_BROADCAST,
		.aperture_index = 0U,
		.element_index_mask = BIT(0),
		.element_index = 0U,
		.dt_mmio = NULL,
		.name = {'\0'},
		.start_abs_pa = addr_map_nvlw0_nvldl_multi_base_r(),
		.end_abs_pa = addr_map_nvlw0_nvldl_multi_limit_r(),
		.start_pa = 0ULL,
		.end_pa = 0ULL,
		.base_pa = 0ULL,
		.alist = th500_nvltx_alist,
		.alist_size = ARRAY_SIZE(th500_nvltx_alist),
		.fake_registers = NULL,
	},
	{
		.element_type = IP_ELEMENT_BROADCAST,
		.aperture_index = 1U,
		.element_index_mask = BIT(1),
		.element_index = 1U,
		.dt_mmio = NULL,
		.name = {'\0'},
		.start_abs_pa = addr_map_nvlw0_nvltlc_multi_base_r(),
		.end_abs_pa = addr_map_nvlw0_nvltlc_multi_limit_r(),
		.start_pa = 0ULL,
		.end_pa = 0ULL,
		.base_pa = 0ULL,
		.alist = th500_nvltx_alist,
		.alist_size = ARRAY_SIZE(th500_nvltx_alist),
		.fake_registers = NULL,
	},
};

static struct hwpm_ip_aperture th500_nvltx_inst1_broadcast_element_static_array[
	TH500_HWPM_IP_NVLTX_NUM_BROADCAST_PER_INST] = {
	{
		.element_type = IP_ELEMENT_BROADCAST,
		.aperture_index = 0U,
		.element_index_mask = BIT(0),
		.element_index = 0U,
		.dt_mmio = NULL,
		.name = {'\0'},
		.start_abs_pa = addr_map_nvlw1_nvldl_multi_base_r(),
		.end_abs_pa = addr_map_nvlw1_nvldl_multi_limit_r(),
		.start_pa = 0ULL,
		.end_pa = 0ULL,
		.base_pa = 0ULL,
		.alist = th500_nvltx_alist,
		.alist_size = ARRAY_SIZE(th500_nvltx_alist),
		.fake_registers = NULL,
	},
	{
		.element_type = IP_ELEMENT_BROADCAST,
		.aperture_index = 1U,
		.element_index_mask = BIT(1),
		.element_index = 1U,
		.dt_mmio = NULL,
		.name = {'\0'},
		.start_abs_pa = addr_map_nvlw1_nvltlc_multi_base_r(),
		.end_abs_pa = addr_map_nvlw1_nvltlc_multi_limit_r(),
		.start_pa = 0ULL,
		.end_pa = 0ULL,
		.base_pa = 0ULL,
		.alist = th500_nvltx_alist,
		.alist_size = ARRAY_SIZE(th500_nvltx_alist),
		.fake_registers = NULL,
	},
};

/* IP instance array */
struct hwpm_ip_inst th500_nvltx_inst_static_array[
	TH500_HWPM_IP_NVLTX_NUM_INSTANCES] = {
	{
		.hw_inst_mask = BIT(0),
		.num_core_elements_per_inst =
			TH500_HWPM_IP_NVLTX_NUM_CORE_ELEMENT_PER_INST,
		.element_info = {
			/*
			 * Instance info corresponding to
			 * TEGRA_HWPM_APERTURE_TYPE_PERFMUX
			 */
			{
				.num_element_per_inst =
					TH500_HWPM_IP_NVLTX_NUM_PERFMUX_PER_INST,
				.element_static_array =
					th500_nvltx_inst0_perfmux_element_static_array,
				/* NOTE: range should be in ascending order */
				.range_start = addr_map_nvlw0_nvldl0_base_r(),
				.range_end = addr_map_nvlw0_nvltlc5_limit_r(),
				.element_stride = addr_map_nvlw0_nvltlc0_limit_r() -
					addr_map_nvlw0_nvltlc0_base_r() + 1ULL,
				.element_slots = 0U,
				.element_arr = NULL,
			},
			/*
			 * Instance info corresponding to
			 * TEGRA_HWPM_APERTURE_TYPE_BROADCAST
			 */
			{
				.num_element_per_inst =
					TH500_HWPM_IP_NVLTX_NUM_BROADCAST_PER_INST,
				.element_static_array =
					th500_nvltx_inst0_broadcast_element_static_array,
				.range_start = addr_map_nvlw0_nvldl_multi_base_r(),
				.range_end = addr_map_nvlw0_nvltlc_multi_limit_r(),
				.element_stride = addr_map_nvlw0_nvltlc_multi_limit_r() -
					addr_map_nvlw0_nvltlc_multi_base_r() + 1ULL,
				.element_slots = 0U,
				.element_arr = NULL,
			},
			/*
			 * Instance info corresponding to
			 * TEGRA_HWPM_APERTURE_TYPE_PERFMON
			 */
			{
				.num_element_per_inst =
					TH500_HWPM_IP_NVLTX_NUM_PERFMON_PER_INST,
				.element_static_array =
					th500_nvltx_inst0_perfmon_element_static_array,
				.range_start = addr_map_rpg_pm_nvltx0_base_r(),
				.range_end = addr_map_rpg_pm_nvltx11_limit_r(),
				.element_stride = addr_map_rpg_pm_nvltx0_limit_r() -
					addr_map_rpg_pm_nvltx0_base_r() + 1ULL,
				.element_slots = 0U,
				.element_arr = NULL,
			},
		},

		.ip_ops = {
			.ip_dev = NULL,
			.hwpm_ip_pm = NULL,
			.hwpm_ip_reg_op = NULL,
			.fd = TEGRA_HWPM_IP_DEBUG_FD_INVALID,
		},

		.element_fs_mask = 0U,
		.dev_name = "",
	},
	{
		.hw_inst_mask = BIT(1),
		.num_core_elements_per_inst =
			TH500_HWPM_IP_NVLTX_NUM_CORE_ELEMENT_PER_INST,
		.element_info = {
			/*
			 * Instance info corresponding to
			 * TEGRA_HWPM_APERTURE_TYPE_PERFMUX
			 */
			{
				.num_element_per_inst =
					TH500_HWPM_IP_NVLTX_NUM_PERFMUX_PER_INST,
				.element_static_array =
					th500_nvltx_inst1_perfmux_element_static_array,
				/* NOTE: range should be in ascending order */
				.range_start = addr_map_nvlw1_nvldl0_base_r(),
				.range_end = addr_map_nvlw1_nvltlc5_limit_r(),
				.element_stride = addr_map_nvlw1_nvltlc0_limit_r() -
					addr_map_nvlw1_nvltlc0_base_r() + 1ULL,
				.element_slots = 0U,
				.element_arr = NULL,
			},
			/*
			 * Instance info corresponding to
			 * TEGRA_HWPM_APERTURE_TYPE_BROADCAST
			 */
			{
				.num_element_per_inst =
					TH500_HWPM_IP_NVLTX_NUM_BROADCAST_PER_INST,
				.element_static_array =
					th500_nvltx_inst1_broadcast_element_static_array,
				.range_start = addr_map_nvlw1_nvldl_multi_base_r(),
				.range_end = addr_map_nvlw1_nvltlc_multi_limit_r(),
				.element_stride = addr_map_nvlw1_nvltlc_multi_limit_r() -
					addr_map_nvlw1_nvltlc_multi_base_r() + 1ULL,
				.element_slots = 0U,
				.element_arr = NULL,
			},
			/*
			 * Instance info corresponding to
			 * TEGRA_HWPM_APERTURE_TYPE_PERFMON
			 */
			{
				.num_element_per_inst =
					TH500_HWPM_IP_NVLTX_NUM_PERFMON_PER_INST,
				.element_static_array =
					th500_nvltx_inst1_perfmon_element_static_array,
				.range_start = addr_map_rpg_pm_nvltx0_base_r(),
				.range_end = addr_map_rpg_pm_nvltx11_limit_r(),
				.element_stride = addr_map_rpg_pm_nvltx0_limit_r() -
					addr_map_rpg_pm_nvltx0_base_r() + 1ULL,
				.element_slots = 0U,
				.element_arr = NULL,
			},
		},

		.ip_ops = {
			.ip_dev = NULL,
			.hwpm_ip_pm = NULL,
			.hwpm_ip_reg_op = NULL,
			.fd = TEGRA_HWPM_IP_DEBUG_FD_INVALID,
		},

		.element_fs_mask = 0U,
		.dev_name = "",
	},
};

/* IP structure */
struct hwpm_ip th500_hwpm_ip_nvltx = {
	.num_instances = TH500_HWPM_IP_NVLTX_NUM_INSTANCES,
	.ip_inst_static_array = th500_nvltx_inst_static_array,

	.inst_aperture_info = {
		/*
		 * Instance info corresponding to
		 * TEGRA_HWPM_APERTURE_TYPE_PERFMUX
		 */
		{
			/* NOTE: range should be in ascending order */
			.range_start = addr_map_nvlw0_nvldl0_base_r(),
			.range_end = addr_map_nvlw1_nvltlc5_limit_r(),
			.inst_stride = addr_map_nvlw0_nvltlc5_limit_r() -
				addr_map_nvlw0_nvldl0_base_r() + 1ULL,
			.inst_slots = 0U,
			.inst_arr = NULL,
		},
		/*
		 * Instance info corresponding to
		 * TEGRA_HWPM_APERTURE_TYPE_BROADCAST
		 */
		{
			.range_start = addr_map_nvlw0_nvldl_multi_base_r(),
			.range_end = addr_map_nvlw1_nvltlc_multi_limit_r(),
			.inst_stride = addr_map_nvlw0_nvltlc_multi_limit_r() -
				addr_map_nvlw0_nvldl_multi_base_r() + 1ULL,
			.inst_slots = 0U,
			.inst_arr = NULL,
		},
		/*
		 * Instance info corresponding to
		 * TEGRA_HWPM_APERTURE_TYPE_PERFMON
		 */
		{
			.range_start = addr_map_rpg_pm_nvltx0_base_r(),
			.range_end = addr_map_rpg_pm_nvltx11_limit_r(),
			.inst_stride = addr_map_rpg_pm_nvltx5_limit_r() -
				addr_map_rpg_pm_nvltx0_base_r() + 1ULL,
			.inst_slots = 0U,
			.inst_arr = NULL,
		},
	},

	.dependent_fuse_mask = TEGRA_HWPM_FUSE_SECURITY_MODE_MASK | TEGRA_HWPM_FUSE_HWPM_GLOBAL_DISABLE_MASK,
	.override_enable = false,
	.inst_fs_mask = 0U,
	.resource_status = TEGRA_HWPM_RESOURCE_STATUS_INVALID,
	.reserved = false,
};
