/* SPDX-License-Identifier: GPL-2.0-only OR MIT
 * SPDX-FileCopyrightText: Copyright (c) 2020-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved. */
/*
 * This file is autogenerated.  Do not edit.
 */

#ifndef NVGPU_GB20C_REGOPS_AUTO_GENERATED_ALLOWLIST_H
#define NVGPU_GB20C_REGOPS_AUTO_GENERATED_ALLOWLIST_H

#include <nvgpu/types.h>

struct nvgpu_pm_resource_register_range;

u32 gb20c_get_hwpm_perfmon_register_stride(void);
u32 gb20c_get_hwpm_router_register_stride(void);
u32 gb20c_get_hwpm_pma_channel_register_stride(void);
u32 gb20c_get_hwpm_pma_trigger_register_stride(void);
u32 gb20c_get_smpc_register_stride(void);
u32 gb20c_get_hwpm_perfmon_gpc_reg_base(void);
u32 gb20c_get_hwpm_perfmon_fbp_reg_base(void);
u32 gb20c_get_hwpm_perfmon_sys_reg_base(void);
u32 gb20c_get_hwpm_perfmon_gpc_reg_stride(void);
u32 gb20c_get_hwpm_router_gpc_reg_base(void);
u32 gb20c_get_hwpm_router_fbp_reg_base(void);
u32 gb20c_get_hwpm_router_sys_reg_base(void);
u32 gb20c_get_hwpm_router_gpc_reg_stride(void);
u32 gb20c_get_hwpm_pma_channel_cblock_reg_stride(void);
u32 gb20c_get_hwpm_pma_channel_reg_base(void);
u32 gb20c_get_hwpm_pma_trigger_reg_base(void);
u32 gb20c_get_hwpm_pmasys_command_slice_stride(void);
u32 gb20c_get_hwpm_hem_sys0_base(void);
u32 gb20c_get_hwpm_hem_sys0_stride(void);
u32 gb20c_get_cau_register_stride(void);
u32 gb20c_get_hwpm_gpc0_tpc0_cau_base(void);
u32 gb20c_get_hwpm_tpc_cau_range_stride(void);
u32 gb20c_get_hwpm_perf_pmasys_reg_base(void);
u32 gb20c_get_hwpm_perf_ccuprof_gpc0_reg_base(void);
u32 gb20c_get_hwpm_perf_ccuprof_gpcs_reg_base(void);
u32 gb20c_get_hwpm_perf_ccuprof_gpc_reg_stride(void);
u32 gb20c_get_hwpm_perf_ccuprof_unit_reg_stride(void);
u32 gb20c_get_hwpm_perf_ccuprof_units_per_gpc(void);
u32 gb20c_get_hwpm_perf_ccuprof_fbp0_reg_base(void);
u32 gb20c_get_hwpm_perf_ccuprof_fbps_reg_base(void);
u32 gb20c_get_hwpm_perf_ccuprof_fbp_reg_stride(void);
u32 gb20c_get_hwpm_perf_ccuprof_units_per_fbp(void);
u32 gb20c_get_hwpm_gpc0_tpc0_mpc_ccuprof_ulcmux_cntl0(void);
u32 gb20c_get_hwpm_ltc0_lts0_ccuprof_ulcmux_cntl0(void);

const u32 *gb20c_get_hwpm_perfmon_register_offset_allowlist(u32 *count);
const u32 *gb20c_get_hwpm_router_register_offset_allowlist(u32 *count);
const u32 *gb20c_get_hwpm_pma_channel_register_offset_allowlist(u32 *count);
const u32 *gb20c_get_hwpm_pma_trigger_register_offset_allowlist(u32 *count);
const u32 *gb20c_get_smpc_register_offset_allowlist(u32 *count);
const u32 *gb20c_get_cau_register_offset_allowlist(u32 *count);
const u32 *gb20c_get_hes_register_offset_allowlist(u32 *count);
const u32 *gb20c_get_ccuprof_register_offset_allowlist(u32 *count);

const struct nvgpu_pm_resource_register_range
	*gb20c_get_hep_register_ranges(u32 *count);
const struct nvgpu_pm_resource_register_range
	*gb20c_get_hwpm_perfmon_register_ranges(u32 *count);
const struct nvgpu_pm_resource_register_range
	*gb20c_get_hwpm_router_register_ranges(u32 *count);
const struct nvgpu_pm_resource_register_range
	*gb20c_get_hwpm_pma_channel_register_ranges(u32 *count);
const struct nvgpu_pm_resource_register_range
	*gb20c_get_hwpm_pma_trigger_register_ranges(u32 *count);
const struct nvgpu_pm_resource_register_range
	*gb20c_get_smpc_register_ranges(u32 *count);
const struct nvgpu_pm_resource_register_range
	*gb20c_get_hwpm_perfmux_register_ranges(u32 *count);
const struct nvgpu_pm_resource_register_range
	*gb20c_get_hwpm_pc_sampler_register_ranges(u32 *count);
const struct nvgpu_pm_resource_register_range
	*gb20c_get_cau_register_ranges(u32 *count);
const struct nvgpu_pm_resource_register_range
	*gb20c_get_sys_misc_device_register_ranges(u32 *count);
const struct nvgpu_pm_resource_register_range
	*gb20c_get_hes_register_ranges(u32 *count);
const struct nvgpu_pm_resource_register_range
	*gb20c_get_hwpm_mm_register_ranges(u32 *count);

/* This is autogenerated file. Do not edit manually. */

#endif /* NVGPU_GB20C_REGOPS_AUTO_GENERATED_ALLOWLIST_H */
