/* SPDX-License-Identifier: GPL-2.0-only OR MIT
 * SPDX-FileCopyrightText: Copyright (c) 2020-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 */
 /* This file is autogenerated.  Do not edit.
 */

#ifndef NVGPU_GB10B_REGOPS_ALLOWLIST_H
#define NVGPU_GB10B_REGOPS_ALLOWLIST_H

#include <nvgpu/types.h>

struct nvgpu_pm_resource_register_range;

u32 gb10b_get_hwpm_perfmon_register_stride(void);
u32 gb10b_get_hwpm_router_register_stride(void);
u32 gb10b_get_hwpm_pma_channel_register_stride(void);
u32 gb10b_get_hwpm_pma_trigger_register_stride(void);
u32 gb10b_get_smpc_register_stride(void);
u32 gb10b_get_cau_register_stride(void);

const u32 *gb10b_get_hwpm_perfmon_register_offset_allowlist(u32 *count);
const u32 *gb10b_get_hwpm_router_register_offset_allowlist(u32 *count);
const u32 *gb10b_get_hwpm_pma_channel_register_offset_allowlist(u32 *count);
const u32 *gb10b_get_hwpm_pma_trigger_register_offset_allowlist(u32 *count);
const u32 *gb10b_get_smpc_register_offset_allowlist(u32 *count);
const u32 *gb10b_get_cau_register_offset_allowlist(u32 *count);

const struct nvgpu_pm_resource_register_range
	*gb10b_get_hwpm_perfmon_register_ranges(u32 *count);
const struct nvgpu_pm_resource_register_range
	*gb10b_get_hwpm_router_register_ranges(u32 *count);
const struct nvgpu_pm_resource_register_range
	*gb10b_get_hwpm_pma_channel_register_ranges(u32 *count);
const struct nvgpu_pm_resource_register_range
	*gb10b_get_hwpm_pma_trigger_register_ranges(u32 *count);
const struct nvgpu_pm_resource_register_range
	*gb10b_get_smpc_register_ranges(u32 *count);
const struct nvgpu_pm_resource_register_range
	*gb10b_get_hwpm_perfmux_register_ranges(u32 *count);
const struct nvgpu_pm_resource_register_range
	*gb10b_get_hwpm_pc_sampler_register_ranges(u32 *count);
const struct nvgpu_pm_resource_register_range
	*gb10b_get_cau_register_ranges(u32 *count);
const struct nvgpu_pm_resource_register_range
	*gb10b_get_hes_register_ranges(u32 *count);
const struct nvgpu_pm_resource_register_range
	*gb10b_get_hwpm_mm_register_ranges(u32 *count);
bool gb10b_is_hwpm_pma_reg_context_switched(void);

#endif /* NVGPU_GB10B_REGOPS_ALLOWLIST_H */
