/* SPDX-License-Identifier: GPL-2.0-only OR MIT
 * SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved. */
/*
 * This file is autogenerated.  Do not edit.
 */

#ifndef NVGPU_GB20C_USER_ACCESS_MAP_H
#define NVGPU_GB20C_USER_ACCESS_MAP_H

#include <nvgpu/types.h>

struct regop_offset_range;

const struct regop_offset_range *gb20c_get_global_allowlist_ranges(void);
u64 gb20c_get_global_allowlist_ranges_count(void);

#endif /* NVGPU_GB20C_USER_ACCESS_MAP_H */
