# SPDX-License-Identifier: GPL-2.0-only
# SPDX-FileCopyrightText: Copyright (c) 2023-2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.

snd-soc-tegra-utils-objs		:= tegra_asoc_utils.o tegra_asoc_machine.o \
					   tegra_isomgr_bw.o tegra_codecs.o
snd-soc-tegra210-ahub-objs		:= tegra210_ahub.o
snd-soc-tegra210-dmic-objs		:= tegra210_dmic.o
snd-soc-tegra210-i2s-objs		:= tegra210_i2s.o
snd-soc-tegra186-dspk-objs		:= tegra186_dspk.o
snd-soc-tegra210-admaif-objs		:= tegra210_admaif.o
snd-soc-tegra210-amx-objs		:= tegra210_amx.o
snd-soc-tegra210-adx-objs		:= tegra210_adx.o
snd-soc-tegra210-mixer-objs		:= tegra210_mixer.o
snd-soc-tegra210-sfc-objs		:= tegra210_sfc.o
snd-soc-tegra210-afc-objs		:= tegra210_afc.o
snd-soc-tegra210-mvc-objs		:= tegra210_mvc.o
snd-soc-tegra210-iqc-objs		:= tegra210_iqc.o
snd-soc-tegra186-asrc-objs		:= tegra186_asrc.o
snd-soc-tegra186-arad-objs		:= tegra186_arad.o
snd-soc-tegra210-ope-objs		:= tegra210_ope.o tegra210_peq.o \
					   tegra210_mbdrc.o
snd-soc-tegra-machine-driver-objs	:= tegra_machine_driver.o

obj-m += snd-soc-tegra-utils.o
obj-m += snd-soc-tegra210-dmic.o
obj-m += snd-soc-tegra210-ahub.o
obj-m += snd-soc-tegra210-i2s.o
obj-m += snd-soc-tegra186-dspk.o
obj-m += snd-soc-tegra210-admaif.o
obj-m += snd-soc-tegra210-amx.o
obj-m += snd-soc-tegra210-adx.o
obj-m += snd-soc-tegra210-mixer.o
obj-m += snd-soc-tegra210-sfc.o
obj-m += snd-soc-tegra210-afc.o
obj-m += snd-soc-tegra210-mvc.o
obj-m += snd-soc-tegra210-iqc.o
obj-m += snd-soc-tegra210-ope.o
obj-m += snd-soc-tegra186-arad.o
obj-m += snd-soc-tegra186-asrc.o
obj-m += snd-soc-tegra-machine-driver.o
