# SPDX-License-Identifier: GPL-2.0-or-later
#
# Würth Elektronik WSEN-ISDS IIO driver
#

obj-$(CONFIG_WSEN_ISDS) += wsen_isds.o
wsen_isds-y := wsen_isds_core.o

obj-$(CONFIG_WSEN_ISDS_I2C) += wsen_isds_i2c.o
